(()=>{
'use strict';

/* Static Cellbound combat catalogue.
   Kept separate from the hot simulation engine so class/balance data does not
   keep the core runtime in one oversized source file. */
const CLASS_COLORS={
 'Death Knight':'#C41E3A','Demon Hunter':'#A330C9','Druid':'#FF7C0A','Evoker':'#33937F',
 'Hunter':'#AAD372','Mage':'#3FC7EB','Warrior':'#C69B6D','Paladin':'#F48CBA',
 'Priest':'#FFFFFF','Rogue':'#FFF468','Shaman':'#0070DD','Warlock':'#8788EE','Monk':'#00FF98'
};

const RESOURCE_DEFS={
 'Death Knight':{name:'Runic Power',max:100,start:20,regen:2},
 'Demon Hunter':{name:'Fury',max:100,start:30,regen:9},
 Druid:{name:'Mana',max:100,start:100,regen:7},
 Evoker:{name:'Essence',max:5,start:5,regen:.45},
 Hunter:{name:'Focus',max:100,start:80,regen:9},
 Mage:{name:'Mana',max:100,start:100,regen:5},
 Warrior:{name:'Rage',max:100,start:20,regen:7},
 Paladin:{name:'Mana',max:100,start:100,regen:6},
 'Priest|Shadow':{name:'Insanity',max:100,start:0,regen:0},
 'Druid|Balance':{name:'Astral Power',max:100,start:0,regen:0},
 Priest:{name:'Mana',max:100,start:100,regen:7},
 'Shaman|Elemental':{name:'Maelstrom',max:100,start:0,regen:0},
 Shaman:{name:'Mana',max:100,start:100,regen:7},
 'Warlock|Destruction':{name:'Soul Shards',max:5,start:0,regen:0},
 Warlock:{name:'Mana',max:100,start:100,regen:5.5},
 'Monk|Brewmaster':{name:'Energy',max:100,start:100,regen:11},
 'Monk|Mistweaver':{name:'Mana',max:100,start:100,regen:7},
 'Monk|Windwalker':{name:'Energy',max:100,start:100,regen:12},
 Rogue:{name:'Energy',max:100,start:100,regen:13}
};

const CLASS_BUFFS={
 'Death Knight':{id:'class-buff-horn-of-winter',name:'Horn of Winter',scope:'party',duration:60000,cooldown:180000,effect:{outgoingDamage:.03,resourceRegen:.04}},
 'Demon Hunter':{id:'class-buff-demonic-momentum',name:'Demonic Momentum',scope:'self',duration:60000,cooldown:180000,effect:{outgoingDamage:.15,haste:.10,resourceRegen:.15}},
 Hunter:{id:'class-buff-predators-focus',name:"Predator's Focus",scope:'self',duration:60000,cooldown:180000,effect:{outgoingDamage:.15,haste:.10,resourceRegen:.10}},
 Rogue:{id:'class-buff-killing-tempo',name:'Killing Tempo',scope:'self',duration:60000,cooldown:180000,effect:{outgoingDamage:.15,critBonus:.10}},
 Warrior:{id:'class-buff-battle-fury',name:'Battle Fury',scope:'self',duration:60000,cooldown:180000,effect:{outgoingDamage:.15,threatBonus:.15,incomingDamageReduction:.10}},
 Mage:{id:'class-buff-arcane-empowerment',name:'Arcane Empowerment',scope:'party',duration:60000,cooldown:180000,effect:{outgoingDamage:.05}},
 'Priest|Shadow':{id:'class-buff-shadow-inspiration',name:'Shadow Inspiration',scope:'party',duration:60000,cooldown:180000,effect:{outgoingDamage:.04,resourceRegen:.04}},
 Priest:{id:'class-buff-divine-inspiration',name:'Divine Inspiration',scope:'party',duration:60000,cooldown:180000,effect:{outgoingHealing:.05,incomingHealing:.05}},
 Druid:{id:'class-buff-wild-communion',name:'Wild Communion',scope:'party',duration:60000,cooldown:180000,effect:{outgoingDamage:.04,outgoingHealing:.04,resourceRegen:.04}},
 Paladin:{id:'class-buff-blessing-resolve',name:'Blessing of Resolve',scope:'party',duration:60000,cooldown:180000,effect:{incomingDamageReduction:.06}},
 Shaman:{id:'class-buff-bloodlust',name:'Bloodlust',scope:'party',duration:60000,cooldown:180000,effect:{haste:.10,resourceRegen:.05}},
 Warlock:{id:'class-buff-demonic-pact',name:'Demonic Pact',scope:'party',duration:60000,cooldown:180000,effect:{outgoingDamage:.04}},
 Monk:{id:'class-buff-mystic-touch',name:'Mystic Touch',scope:'party',duration:60000,cooldown:180000,effect:{outgoingDamage:.03,outgoingHealing:.03}},
 Evoker:{id:'class-buff-draconic-resonance',name:'Draconic Resonance',scope:'party',duration:60000,cooldown:180000,effect:{haste:.06}}
};

const ABILITIES={
 'Death Knight':[
  {id:'heart-strike',name:'Heart Strike',kind:'damage',role:'tank',spec:'Blood',unlockLevel:1,desc:'A high-threat strike that generates Runic Power.',range:5,damage:18,cost:0,gain:16,gcd:1200,cd:0,threat:2.6},
  {id:'death-strike',name:'Death Strike',kind:'damage',role:'tank',spec:'Blood',unlockLevel:1,desc:'Spend Runic Power to strike and heal from damage taken recently.',range:5,damage:22,cost:35,gcd:1200,cd:0,threat:2.2},
  {id:'dark-command',name:'Dark Command',kind:'taunt',role:'tank',spec:'Blood',unlockLevel:1,desc:'Command an enemy to attack the Death Knight.',range:30,cost:0,gcd:0,cd:8000,threat:5},
  {id:'mind-freeze',name:'Mind Freeze',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast with frozen runic force.',range:15,cost:0,gcd:0,cd:15000},
  {id:'marrowrend',name:'Marrowrend',kind:'damage',role:'tank',spec:'Blood',unlockLevel:1,desc:'Generate Runic Power and reinforce Bone Shield.',range:5,damage:17,cost:0,gain:14,gcd:1200,cd:4500,threat:2.4},
  {id:'blood-boil',name:'Blood Boil',kind:'damage',role:'tank',spec:'Blood',unlockLevel:4,desc:'Boil the blood of nearby enemies for heavy pack threat.',range:8,damage:16,cost:0,gain:10,gcd:1200,cd:7000,cleave:3,threat:2.8,damageType:'magic'},
  {id:'death-and-decay-blood',name:'Death and Decay',kind:'damage',role:'tank',spec:'Blood',unlockLevel:7,desc:'Corrupt the ground beneath enemies with shadow damage.',range:15,damage:17,cost:10,gcd:1200,cd:12000,cleave:3,threat:2.5,damageType:'magic'},
  {id:'rune-tap',name:'Rune Tap',kind:'defensive',role:'tank',spec:'Blood',unlockLevel:1,desc:'Briefly reduce incoming damage.',duration:5000,damageReduction:.20,gcd:0,cd:30000},
  {id:'dancing-rune-weapon',name:'Dancing Rune Weapon',kind:'defensive',role:'tank',spec:'Blood',unlockLevel:1,desc:'Summon a spectral weapon that reinforces defence and threat.',duration:9000,damageReduction:.22,gcd:0,cd:75000},
  {id:'vampiric-blood',name:'Vampiric Blood',kind:'defensive',role:'tank',spec:'Blood',unlockLevel:1,desc:'Empower your blood, restoring health and greatly improving survival.',duration:10000,damageReduction:.25,selfHealPct:.18,gcd:0,cd:90000},

  {id:'obliterate',name:'Obliterate',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'A brutal melee strike that generates Runic Power.',range:5,damage:28,cost:0,gain:18,gcd:1200,cd:4500},
  {id:'frost-strike',name:'Frost Strike',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Spend Runic Power on a weapon strike infused with frost.',range:5,damage:26,cost:28,gcd:1200,cd:0,damageType:'magic'},
  {id:'howling-blast',name:'Howling Blast',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Blast the target and nearby enemies with freezing wind.',range:25,damage:18,cost:0,gain:12,gcd:1200,cd:6000,cleave:2,damageType:'magic'},
  {id:'remorseless-winter',name:'Remorseless Winter',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Surround yourself with a freezing storm that cleaves nearby enemies.',range:8,damage:24,cost:18,gcd:1200,cd:14000,cleave:3,damageType:'magic'},
  {id:'frostscythe',name:'Frostscythe',kind:'damage',role:'dps',spec:'Frost',unlockLevel:7,desc:'Sweep a frozen blade through several enemies.',range:7,damage:21,cost:0,gain:10,gcd:1200,cd:9000,cleave:3,damageType:'magic'},
  {id:'frostwyrms-fury',name:"Frostwyrm's Fury",kind:'damage',role:'dps',spec:'Frost',unlockLevel:11,desc:'Call a frostwyrm across the battlefield for heavy cleave damage.',range:30,damage:38,cost:35,gcd:1500,cast:1000,cd:45000,cleave:4,damageType:'magic'},
  {id:'breath-of-sindragosa',name:'Breath of Sindragosa',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Unleash a devastating cone of frost into the enemy pack.',range:20,damage:45,cost:50,gcd:1500,cast:1200,cd:60000,cleave:4,damageType:'magic'},
  {id:'icebound-fortitude',name:'Icebound Fortitude',kind:'defensive',role:'dps',spec:'Frost',unlockLevel:8,desc:'Harden yourself against incoming damage.',duration:8000,damageReduction:.25,gcd:0,cd:75000},

  {id:'festering-strike',name:'Festering Strike',kind:'damage',role:'dps',spec:'Unholy',unlockLevel:1,desc:'Strike the target, generate Runic Power and apply Festering Wounds.',range:5,damage:20,cost:0,gain:15,gcd:1200,cd:3500},
  {id:'scourge-strike',name:'Scourge Strike',kind:'damage',role:'dps',spec:'Unholy',unlockLevel:1,desc:'Burst Festering Wounds for additional shadow damage.',range:5,damage:19,cost:0,gain:8,gcd:1200,cd:0,damageType:'magic'},
  {id:'death-coil',name:'Death Coil',kind:'damage',role:'dps',spec:'Unholy',unlockLevel:1,desc:'Spend Runic Power to hurl death magic at the target.',range:30,damage:27,cost:30,gcd:1200,cd:0,damageType:'magic'},
  {id:'outbreak',name:'Outbreak',kind:'damage',role:'dps',spec:'Unholy',unlockLevel:1,desc:'Infect the target with a damaging plague.',range:30,damage:10,cost:0,gain:8,gcd:1200,cd:7000,damageType:'magic'},
  {id:'death-and-decay-unholy',name:'Death and Decay',kind:'damage',role:'dps',spec:'Unholy',unlockLevel:6,desc:'Corrupt the ground beneath enemies with shadow damage.',range:15,damage:17,cost:10,gcd:1200,cd:12000,cleave:3,damageType:'magic'},
  {id:'dark-transformation',name:'Dark Transformation',kind:'pet-command',role:'dps',spec:'Unholy',unlockLevel:1,desc:'Empower your permanent Ghoul into a savage frenzy.',range:30,cost:15,gcd:1000,cd:30000,petCommand:'dark-transformation'},
  {id:'army-of-the-dead',name:'Army of the Dead',kind:'summon',role:'dps',spec:'Unholy',unlockLevel:1,desc:'Summon a pack of temporary ghouls to tear into your enemies.',range:30,cost:35,gcd:1500,cast:1800,cd:75000,duration:14000,summonType:'army-ghoul',summonCount:4},
  {id:'apocalypse',name:'Apocalypse',kind:'summon',role:'dps',spec:'Unholy',unlockLevel:1,desc:'Burst Festering Wounds and summon additional undead attackers.',range:5,cost:30,gcd:1500,cd:45000,duration:12000,summonType:'apocalypse-ghoul',summonCount:2},
  {id:'anti-magic-shell',name:'Anti-Magic Shell',kind:'defensive',role:'dps',spec:'Unholy',unlockLevel:8,desc:'Wrap yourself in anti-magic energy to reduce incoming damage.',duration:8000,damageReduction:.25,gcd:0,cd:75000}
 ],
 'Demon Hunter':[
  {id:'demons-bite',name:"Demon's Bite",kind:'damage',role:'dps',spec:'Havoc',unlockLevel:1,desc:'Generate Fury with a fast warglaive strike.',range:5,damage:16,cost:0,gain:24,gcd:1000,cd:0},
  {id:'chaos-strike',name:'Chaos Strike',kind:'damage',role:'dps',spec:'Havoc',unlockLevel:1,desc:'Spend Fury on a heavy chaos-infused melee strike.',range:5,damage:28,cost:30,gcd:1000,cd:0,damageType:'magic'},
  {id:'blade-dance',name:'Blade Dance',kind:'damage',role:'dps',spec:'Havoc',unlockLevel:1,desc:'Dance through the target and nearby enemies with both warglaives.',range:6,damage:20,cost:25,gcd:1000,cd:8000,cleave:3},
  {id:'throw-glaive',name:'Throw Glaive',kind:'damage',role:'dps',spec:'Havoc',unlockLevel:4,desc:'Throw a warglaive at a distant target while repositioning.',range:20,damage:15,cost:0,gain:8,gcd:1000,cd:6000},
  {id:'eye-beam',name:'Eye Beam',kind:'damage',role:'dps',spec:'Havoc',unlockLevel:6,desc:'Channel fel energy through enemies in front of you.',range:18,damage:32,cost:30,gcd:1000,cast:1200,cd:18000,cleave:3,damageType:'magic'},
  {id:'fel-barrage',name:'Fel Barrage',kind:'damage',role:'dps',spec:'Havoc',unlockLevel:1,desc:'Unleash a violent fel barrage across the enemy pack.',range:18,damage:38,cost:35,gcd:1000,cd:22000,cleave:4,damageType:'magic'},
  {id:'havoc-metamorphosis',name:'Metamorphosis',kind:'damage',role:'dps',spec:'Havoc',unlockLevel:1,desc:'Transform and crash into the target, opening a major demonic burst window.',range:12,damage:40,cost:20,gcd:1000,cd:60000,cleave:2,damageType:'magic'},
  {id:'blur',name:'Blur',kind:'defensive',role:'dps',spec:'Havoc',unlockLevel:10,desc:'Blur your form, reducing incoming damage for 8 seconds.',duration:8000,damageReduction:.30,gcd:0,cd:75000},
  {id:'disrupt',name:'Disrupt',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast with fel force.',range:10,cost:0,gcd:0,cd:15000},

  {id:'shear',name:'Shear',kind:'damage',role:'tank',spec:'Vengeance',unlockLevel:1,desc:'Rip into the target, generating Fury and a Soul Fragment.',range:5,damage:16,cost:0,gain:18,gcd:1000,cd:0,threat:2.6},
  {id:'soul-cleave',name:'Soul Cleave',kind:'damage',role:'tank',spec:'Vengeance',unlockLevel:1,desc:'Spend Fury and consume Soul Fragments to damage the target and heal yourself.',range:5,damage:21,cost:30,gcd:1000,cd:0,threat:2.4,damageType:'magic'},
  {id:'infernal-strike',name:'Infernal Strike',kind:'damage',role:'tank',spec:'Vengeance',unlockLevel:1,desc:'Leap into the pack in a burst of fel fire and heavy threat.',range:15,damage:17,cost:10,gain:8,gcd:1000,cd:10000,cleave:3,threat:2.8,damageType:'magic'},
  {id:'torment',name:'Torment',kind:'taunt',role:'tank',spec:'Vengeance',unlockLevel:1,desc:'Torment the enemy and force its attention onto the Demon Hunter.',range:30,cost:0,gcd:0,cd:8000,threat:5},
  {id:'sigil-of-flame',name:'Sigil of Flame',kind:'damage',role:'tank',spec:'Vengeance',unlockLevel:1,desc:'Burn enemies in a fel sigil for area damage and pack threat.',range:18,damage:20,cost:12,gain:8,gcd:1000,cd:12000,cleave:3,threat:2.7,damageType:'magic'},
  {id:'demon-spikes',name:'Demon Spikes',kind:'defensive',role:'tank',spec:'Vengeance',unlockLevel:5,desc:'Harden your body with demonic spikes to reduce incoming damage.',duration:7000,damageReduction:.25,gcd:0,cd:18000},
  {id:'fiery-brand',name:'Fiery Brand',kind:'defensive',role:'tank',spec:'Vengeance',unlockLevel:9,desc:'Brand the enemy with fel fire while fortifying yourself against its assault.',duration:8000,damageReduction:.30,gcd:0,cd:60000},
  {id:'spirit-bomb',name:'Spirit Bomb',kind:'damage',role:'tank',spec:'Vengeance',unlockLevel:1,desc:'Consume Soul Fragments in an explosive fel blast that also restores health.',range:10,damage:28,cost:30,gcd:1000,cd:15000,cleave:3,threat:2.9,damageType:'magic'},
  {id:'vengeance-metamorphosis',name:'Metamorphosis',kind:'defensive',role:'tank',spec:'Vengeance',unlockLevel:1,desc:'Transform into a towering demon, restoring health and greatly reducing damage taken.',duration:10000,damageReduction:.35,selfHealPct:.18,gcd:0,cd:90000}
 ],
 Druid:[
  {id:'rejuvenation',name:'Rejuvenation',kind:'heal',role:'healer',spec:'Restoration',unlockLevel:1,desc:'An efficient heal with a short healing-over-time effect.',range:30,heal:22,cost:10,gcd:1500,cast:0,cd:0,hot:8},
  {id:'regrowth',name:'Regrowth',kind:'heal',role:'healer',spec:'Restoration',unlockLevel:1,desc:'A stronger direct heal for injured allies.',range:30,heal:34,cost:18,gcd:1500,cast:1100,cd:0},
  {id:'wild-growth',name:'Wild Growth',kind:'group-heal',role:'healer',spec:'Restoration',unlockLevel:1,desc:'Restore health to the whole party.',range:30,heal:15,cost:22,gcd:1500,cast:0,cd:8000},
  {id:'skull-bash',name:'Skull Bash',kind:'interrupt',role:'healer',spec:'Restoration',unlockLevel:1,desc:'Interrupt an enemy cast.',range:13,cost:0,gcd:0,cd:15000},
  {id:'restoration-wrath',name:'Wrath',kind:'damage',role:'healer',spec:'Restoration',unlockLevel:4,desc:'A ranged nature attack for safe damage windows.',range:30,damage:14,cost:4,gcd:1500,cast:1200,cd:0,damageType:'magic'},
  {id:'barkskin',name:'Barkskin',kind:'defensive',unlockLevel:8,desc:'Reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.20,gcd:0,cd:60000},
  {id:'tranquility',name:'Tranquility',kind:'group-heal',role:'healer',spec:'Restoration',unlockLevel:1,desc:'A powerful emergency party heal with a long cooldown.',range:30,heal:30,cost:32,gcd:1500,cast:2500,cd:30000},

  {id:'wrath',name:'Wrath',kind:'damage',role:'dps',spec:'Balance',unlockLevel:1,desc:'Cast nature magic to generate Astral Power and move toward Lunar Eclipse.',range:35,damage:19,cost:0,gain:10,gcd:1500,cast:1200,cd:0,damageType:'magic',school:'nature'},
  {id:'starfire',name:'Starfire',kind:'damage',role:'dps',spec:'Balance',unlockLevel:1,desc:'Cast arcane stellar magic to generate Astral Power and move toward Solar Eclipse.',range:35,damage:22,cost:0,gain:12,gcd:1500,cast:1450,cd:0,cleave:1,damageType:'magic',school:'arcane'},
  {id:'starsurge',name:'Starsurge',kind:'damage',role:'dps',spec:'Balance',unlockLevel:1,desc:'Spend Astral Power on a heavy single-target astral strike.',range:35,damage:40,cost:40,gcd:1500,cast:0,cd:0,damageType:'magic',school:'astral'},
  {id:'moonfire',name:'Moonfire',kind:'damage',role:'dps',spec:'Balance',unlockLevel:4,desc:'Burn the target with lunar magic that continues dealing damage.',range:35,damage:11,cost:0,gain:6,gcd:1500,cast:0,cd:7000,damageType:'magic',school:'arcane'},
  {id:'sunfire',name:'Sunfire',kind:'damage',role:'dps',spec:'Balance',unlockLevel:6,desc:'Scorch the target with solar nature magic and spread pressure into nearby enemies.',range:35,damage:12,cost:0,gain:6,gcd:1500,cast:0,cd:7000,cleave:2,damageType:'magic',school:'nature'},
  {id:'starfall',name:'Starfall',kind:'damage',role:'dps',spec:'Balance',unlockLevel:1,desc:'Spend Astral Power to call falling stars across the enemy pack.',range:35,damage:32,cost:50,gcd:1500,cast:700,cd:8000,cleave:4,damageType:'magic',school:'astral'},
  {id:'fury-of-elune',name:'Fury of Elune',kind:'damage',role:'dps',spec:'Balance',unlockLevel:1,desc:'Channel an astral beam through the enemy pack while generating Astral Power.',range:35,damage:38,cost:0,gain:24,gcd:1500,cast:1600,cd:30000,cleave:3,damageType:'magic',school:'astral'},
  {id:'celestial-alignment',name:'Celestial Alignment',kind:'damage',role:'dps',spec:'Balance',unlockLevel:1,desc:'Align the heavens and empower Solar and Lunar magic simultaneously.',range:35,damage:36,cost:20,gcd:1500,cast:900,cd:60000,cleave:2,damageType:'magic',school:'astral'},
  {id:'solar-beam',name:'Solar Beam',kind:'interrupt',role:'dps',spec:'Balance',unlockLevel:1,desc:'Silence an enemy cast with focused solar energy.',range:30,cost:0,gcd:0,cd:30000}
 ],
 Evoker:[
  {id:'reversion',name:'Reversion',kind:'heal',role:'healer',spec:'Preservation',unlockLevel:1,desc:'Rewind an ally to a healthier moment and continue healing them briefly.',range:25,heal:24,cost:1,gcd:1500,cast:0,cd:7000,hot:8},
  {id:'verdant-embrace',name:'Verdant Embrace',kind:'heal',role:'healer',spec:'Preservation',unlockLevel:1,desc:'Rush restorative dragon magic into an injured ally.',range:25,heal:35,cost:1,gcd:1500,cast:700,cd:6000},
  {id:'emerald-blossom',name:'Emerald Blossom',kind:'group-heal',role:'healer',spec:'Preservation',unlockLevel:1,desc:'Bloom emerald magic through the party.',range:25,heal:18,cost:2,gcd:1500,cast:1000,cd:8000},
  {id:'dream-breath',name:'Dream Breath',kind:'group-heal',role:'healer',spec:'Preservation',unlockLevel:1,desc:'Breathe restorative energy across the party.',range:25,heal:29,cost:3,gcd:1500,cast:1600,cd:22000},
  {id:'temporal-anomaly',name:'Temporal Anomaly',kind:'group-heal',role:'healer',spec:'Preservation',unlockLevel:8,desc:'Send a temporal pulse through allies for broad recovery.',range:25,heal:16,cost:2,gcd:1500,cast:900,cd:12000},
  {id:'emerald-communion',name:'Emerald Communion',kind:'group-heal',role:'healer',spec:'Preservation',unlockLevel:1,desc:'Commune with emerald magic for a powerful emergency party heal.',range:25,heal:38,cost:4,gcd:1500,cast:1800,cd:60000},
  {id:'preservation-living-flame',name:'Living Flame',kind:'damage',role:'healer',spec:'Preservation',unlockLevel:4,desc:'A safe ranged damage spell for quiet healing windows.',range:25,damage:14,cost:0,gcd:1500,cast:1200,cd:0,damageType:'magic'},
  {id:'quell',name:'Quell',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast with draconic force.',range:25,cost:0,gcd:0,cd:24000},
  {id:'obsidian-scales',name:'Obsidian Scales',kind:'defensive',unlockLevel:8,desc:'Harden your scales to reduce incoming damage.',duration:8000,damageReduction:.25,gcd:0,cd:75000},

  {id:'living-flame',name:'Living Flame',kind:'damage',role:'dps',spec:'Devastation',unlockLevel:1,desc:'Launch a focused bolt of red dragonfire.',range:30,damage:22,cost:0,gcd:1500,cast:1300,cd:0,damageType:'magic'},
  {id:'azure-strike',name:'Azure Strike',kind:'damage',role:'dps',spec:'Devastation',unlockLevel:1,desc:'Strike instantly with blue dragon magic.',range:30,damage:14,cost:0,gcd:1500,cd:0,damageType:'magic'},
  {id:'disintegrate',name:'Disintegrate',kind:'damage',role:'dps',spec:'Devastation',unlockLevel:1,desc:'Spend Essence to tear into the target with blue magic.',range:30,damage:34,cost:2,gcd:1500,cast:1400,cd:0,damageType:'magic'},
  {id:'fire-breath',name:'Fire Breath',kind:'damage',role:'dps',spec:'Devastation',unlockLevel:4,desc:'Breathe red dragonfire through the enemy pack.',range:22,damage:27,cost:1,gcd:1500,cast:1200,cd:14000,cleave:3,damageType:'magic'},
  {id:'pyre',name:'Pyre',kind:'damage',role:'dps',spec:'Devastation',unlockLevel:6,desc:'Spend Essence to explode dragonfire across nearby enemies.',range:30,damage:25,cost:2,gcd:1500,cd:6000,cleave:3,damageType:'magic'},
  {id:'eternity-surge',name:'Eternity Surge',kind:'damage',role:'dps',spec:'Devastation',unlockLevel:1,desc:'Release a devastating blast of blue dragon magic.',range:30,damage:40,cost:3,gcd:1500,cast:1700,cd:18000,cleave:2,damageType:'magic'},
  {id:'dragonrage',name:'Dragonrage',kind:'damage',role:'dps',spec:'Devastation',unlockLevel:1,desc:'Unleash the full fury of the dragonflights and enter a major burst window.',range:30,damage:38,cost:2,gcd:1500,cd:60000,cleave:3,damageType:'magic'}
 ],
 Hunter:[
  {id:'aimed-shot',name:'Aimed Shot',kind:'damage',role:'dps',spec:'Marksman',unlockLevel:1,desc:'A slow, heavy ranged shot.',range:35,damage:36,cost:35,gcd:1500,cast:1500,cd:7000},
  {id:'arcane-shot',name:'Arcane Shot',kind:'damage',role:'dps',spec:'Marksman',unlockLevel:1,desc:'Reliable ranged damage.',range:35,damage:20,cost:20,gcd:1500,cd:0},
  {id:'steady-shot',name:'Steady Shot',kind:'damage',role:'dps',spec:'Marksman',unlockLevel:1,desc:'Generate Focus while maintaining ranged pressure.',range:35,damage:12,cost:0,gain:18,gcd:1500,cast:900,cd:0},
  {id:'multi-shot',name:'Multi-Shot',kind:'damage',role:'dps',spec:'Marksman',unlockLevel:5,desc:'Strike the target and nearby enemies.',range:35,damage:14,cost:30,gcd:1500,cd:6000,cleave:2},
  {id:'kill-shot',name:'Kill Shot',kind:'damage',role:'dps',spec:'Marksman',unlockLevel:1,desc:'A finishing attack that is strongest against weakened enemies.',range:35,damage:29,cost:20,gcd:1500,cd:10000,executeBelow:.20,executeMultiplier:1.85},

  {id:'cobra-shot',name:'Cobra Shot',kind:'damage',role:'dps',spec:'Beast Mastery',unlockLevel:1,desc:'Fire a fast shot while directing your beast, spending Focus for mobile pressure.',range:35,damage:18,cost:25,gcd:1500,cast:0,cd:0},
  {id:'barbed-shot',name:'Barbed Shot',kind:'damage',role:'dps',spec:'Beast Mastery',unlockLevel:1,desc:'Wound the target, generate Focus and drive your permanent beast into a frenzy.',range:35,damage:16,cost:0,gain:18,gcd:1500,cast:0,cd:8000},
  {id:'kill-command',name:'Kill Command',kind:'pet-command',role:'dps',spec:'Beast Mastery',unlockLevel:1,desc:'Command your permanent beast to tear into the target.',range:35,cost:30,gcd:1000,cd:7000,petCommand:'kill-command'},
  {id:'beast-multi-shot',name:'Multi-Shot',kind:'damage',role:'dps',spec:'Beast Mastery',unlockLevel:5,desc:'Strike several enemies and trigger Beast Cleave when talented.',range:35,damage:13,cost:30,gcd:1500,cd:6000,cleave:3},
  {id:'dire-beast',name:'Dire Beast',kind:'summon',role:'dps',spec:'Beast Mastery',unlockLevel:1,desc:'Call a temporary beast that attacks your target and generates Focus.',range:35,cost:0,gain:15,gcd:1500,cast:0,cd:24000,duration:12000,summonType:'dire-beast',summonCount:1},
  {id:'stampede',name:'Stampede',kind:'summon',role:'dps',spec:'Beast Mastery',unlockLevel:1,desc:'Call a stampede of beasts through the enemy pack.',range:35,cost:20,gcd:1500,cast:700,cd:45000,duration:9000,summonType:'stampede-beast',summonCount:3},
  {id:'bestial-wrath',name:'Bestial Wrath',kind:'pet-command',role:'dps',spec:'Beast Mastery',unlockLevel:1,desc:'Empower yourself and your permanent beast for a major burst window.',range:35,cost:20,gcd:1000,cd:60000,petCommand:'bestial-wrath'},
  {id:'counter-shot',name:'Counter Shot',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast from range.',range:35,cost:0,gcd:0,cd:24000},
  {id:'survival-instincts',name:'Survival Instincts',kind:'defensive',unlockLevel:13,desc:'Reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.20,gcd:0,cd:75000}
 ],
 Mage:[
  {id:'pyroblast',name:'Pyroblast',kind:'damage',role:'dps',spec:'Arcane',unlockLevel:1,desc:'A slow, devastating ranged spell.',range:35,damage:36,cost:14,gcd:1500,cast:2200,cd:8000,damageType:'magic'},
  {id:'fireball',name:'Fireball',kind:'damage',role:'dps',spec:'Arcane',unlockLevel:1,desc:'Reliable ranged spell damage.',range:35,damage:24,cost:8,gcd:1500,cast:1700,cd:0,damageType:'magic'},
  {id:'fire-blast',name:'Fire Blast',kind:'damage',role:'dps',spec:'Arcane',unlockLevel:1,desc:'An instant burst of damage.',range:35,damage:16,cost:4,gcd:0,cast:0,cd:9000,damageType:'magic'},
  {id:'arcane-barrage',name:'Arcane Barrage',kind:'damage',role:'dps',spec:'Arcane',unlockLevel:5,desc:'An instant ranged attack with a short cooldown.',range:35,damage:25,cost:12,gcd:1500,cd:5000,damageType:'magic'},
  {id:'arcane-ward',name:'Arcane Ward',kind:'defensive',role:'dps',spec:'Arcane',unlockLevel:9,desc:'Reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.25,gcd:0,cd:75000},
  {id:'arcane-nova',name:'Arcane Nova',kind:'damage',role:'dps',spec:'Arcane',unlockLevel:13,desc:'Burst the target and nearby enemies with arcane energy.',range:25,damage:22,cost:18,gcd:1500,cd:10000,cleave:3,damageType:'magic'},

  {id:'frostbolt',name:'Frostbolt',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Launch a bolt of frost and build toward Frost procs.',range:35,damage:20,cost:6,gcd:1500,cast:1450,cd:0,damageType:'magic'},
  {id:'ice-lance',name:'Ice Lance',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'An instant frost shard that becomes deadly against frozen targets.',range:35,damage:14,cost:5,gcd:1500,cast:0,cd:0,damageType:'magic'},
  {id:'flurry',name:'Flurry',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'A rapid sequence of frost bolts that can prepare a Shatter window.',range:35,damage:27,cost:10,gcd:1500,cast:950,cd:8000,damageType:'magic'},
  {id:'blizzard',name:'Blizzard',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Blanket the enemy pack in freezing magic.',range:35,damage:20,cost:16,gcd:1500,cast:1400,cd:8000,cleave:4,damageType:'magic'},
  {id:'frozen-orb',name:'Frozen Orb',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Launch an orb that repeatedly lashes nearby enemies with frost.',range:35,damage:30,cost:18,gcd:1500,cast:700,cd:24000,cleave:3,damageType:'magic'},
  {id:'glacial-spike',name:'Glacial Spike',kind:'damage',role:'dps',spec:'Frost',unlockLevel:1,desc:'Hurl a massive spike of compressed ice for devastating burst.',range:35,damage:48,cost:24,gcd:1500,cast:1800,cd:18000,damageType:'magic'},
  {id:'counterspell',name:'Counterspell',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast from range.',range:35,cost:0,gcd:0,cd:24000},
  {id:'ice-barrier',name:'Ice Barrier',kind:'defensive',role:'dps',spec:'Frost',unlockLevel:8,desc:'Wrap yourself in ice, reducing incoming damage for 8 seconds.',duration:8000,damageReduction:.25,gcd:0,cd:60000}
 ],
 Warrior:[
  {id:'shield-slam',name:'Shield Slam',kind:'damage',role:'tank',unlockLevel:1,desc:'High-threat melee strike.',range:5,damage:21,cost:20,gain:8,gcd:1500,cd:6000,threat:3},
  {id:'revenge',name:'Revenge',kind:'damage',role:'tank',unlockLevel:1,desc:'Reliable tank damage with increased threat.',range:5,damage:16,cost:15,gcd:1500,cd:3000,threat:2.5},
  {id:'taunt',name:'Taunt',kind:'taunt',role:'tank',unlockLevel:1,desc:'Force an enemy to attack the Warrior.',range:30,cost:0,gcd:0,cd:8000,threat:5},
  {id:'mortal-strike',name:'Mortal Strike',kind:'damage',role:'dps',unlockLevel:1,desc:'Heavy single-target weapon damage.',range:5,damage:38,cost:30,gcd:1500,cd:6000},
  {id:'slam',name:'Slam',kind:'damage',role:'dps',unlockLevel:1,desc:'Reliable melee damage.',range:5,damage:24,cost:18,gcd:1500,cd:0},
  {id:'execute',name:'Execute',kind:'damage',role:'dps',unlockLevel:1,desc:'A finishing strike that becomes deadly against weakened enemies.',range:5,damage:30,cost:25,gcd:1500,cd:7000,executeBelow:.25,executeMultiplier:1.9},
  {id:'pummel',name:'Pummel',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast.',range:5,cost:0,gcd:0,cd:15000},
  {id:'shield-wall',name:'Shield Wall',kind:'defensive',role:'tank',unlockLevel:6,desc:'Greatly reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.40,gcd:0,cd:90000},
  {id:'sweeping-strike',name:'Sweeping Strike',kind:'damage',role:'dps',unlockLevel:6,desc:'Strike the target and nearby enemies.',range:5,damage:20,cost:24,gcd:1500,cd:9000,cleave:2},
  {id:'thunder-clap',name:'Thunder Clap',kind:'damage',role:'tank',unlockLevel:10,desc:'Damage several enemies while generating extra threat.',range:8,damage:17,cost:18,gcd:1500,cd:8000,cleave:3,threat:2.7},
  {id:'rallying-guard',name:'Rallying Guard',kind:'defensive',role:'dps',unlockLevel:10,desc:'Brace for danger and reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.20,gcd:0,cd:75000},
  {id:'overpower',name:'Overpower',kind:'damage',role:'dps',unlockLevel:14,desc:'A powerful strike with a short cooldown.',range:5,damage:32,cost:18,gcd:1500,cd:5000}
 ],
 Paladin:[
  {id:'avengers-shield',name:"Avenger's Shield",kind:'damage',role:'tank',unlockLevel:1,desc:'Ranged tank attack with strong threat and cleave.',range:30,damage:20,cost:5,gcd:1500,cd:6000,threat:3,cleave:2},
  {id:'judgement',name:'Judgement',kind:'damage',unlockLevel:1,desc:'A reliable ranged holy attack.',range:30,damage:17,cost:4,gcd:1500,cd:3500,threat:1.7},
  {id:'hand-reckoning',name:'Hand of Reckoning',kind:'taunt',role:'tank',unlockLevel:1,desc:'Force an enemy to attack the Paladin.',range:30,cost:0,gcd:0,cd:8000,threat:5},
  {id:'word-of-glory',name:'Word of Glory',kind:'defensive',role:'tank',unlockLevel:4,desc:'Call on holy power to restore health during sustained pressure.',duration:1000,damageReduction:0,selfHealPct:.16,gcd:0,cd:20000},
  {id:'holy-light',name:'Holy Light',kind:'heal',role:'healer',unlockLevel:1,desc:'A strong efficient direct heal.',range:30,heal:37,cost:14,gcd:1500,cast:1500,cd:0},
  {id:'holy-shock',name:'Holy Shock',kind:'heal',role:'healer',unlockLevel:1,desc:'An instant heal with a short cooldown.',range:30,heal:25,cost:9,gcd:1500,cast:0,cd:6000},
  {id:'light-of-dawn',name:'Light of Dawn',kind:'group-heal',role:'healer',unlockLevel:1,desc:'Restore health to the whole party.',range:30,heal:20,cost:16,gcd:1500,cast:0,cd:6000},
  {id:'rebuke',name:'Rebuke',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast.',range:5,cost:0,gcd:0,cd:15000},
  {id:'ardent-defender',name:'Ardent Defender',kind:'defensive',role:'tank',unlockLevel:6,desc:'Reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.30,gcd:0,cd:75000},
  {id:'flash-of-light',name:'Flash of Light',kind:'heal',role:'healer',unlockLevel:6,desc:'A fast emergency heal at a higher mana cost.',range:30,heal:30,cost:19,gcd:1500,cast:800,cd:0},
  {id:'divine-protection',name:'Divine Protection',kind:'defensive',unlockLevel:10,desc:'Reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.20,gcd:0,cd:60000},
  {id:'consecration',name:'Consecration',kind:'damage',role:'tank',unlockLevel:10,desc:'Damage the target and nearby enemies.',range:8,damage:16,cost:10,gcd:1500,cd:9000,cleave:3,threat:2.2},
  {id:'radiant-wave',name:'Radiant Wave',kind:'group-heal',role:'healer',unlockLevel:14,desc:'A powerful emergency party heal.',range:30,heal:27,cost:30,gcd:1500,cast:1800,cd:22000}
 ],
 Priest:[
  {id:'heal',name:'Heal',kind:'heal',role:'healer',spec:'Holy',unlockLevel:1,desc:'Efficient direct healing.',range:30,heal:35,cost:13,gcd:1500,cast:1400,cd:0},
  {id:'flash-heal',name:'Flash Heal',kind:'heal',role:'healer',spec:'Holy',unlockLevel:1,desc:'Fast emergency healing.',range:30,heal:29,cost:18,gcd:1500,cast:800,cd:0},
  {id:'prayer-healing',name:'Prayer of Healing',kind:'group-heal',role:'healer',spec:'Holy',unlockLevel:1,desc:'Restore health to the whole party.',range:30,heal:24,cost:18,gcd:1500,cast:1700,cd:6500},
  {id:'smite',name:'Smite',kind:'damage',role:'healer',spec:'Holy',unlockLevel:4,desc:'A ranged holy attack for safe damage windows.',range:30,damage:13,cost:4,gcd:1500,cast:1200,cd:0,damageType:'magic'},
  {id:'soul-recall',name:'Soul Recall',kind:'battle-rez',role:'healer',spec:'Holy',unlockLevel:8,desc:'Return a fallen ally to combat. Very long cooldown.',range:30,cost:32,gcd:1500,cast:5000,cd:600000},
  {id:'guardian-spirit',name:'Guardian Spirit',kind:'defensive',role:'healer',spec:'Holy',unlockLevel:12,desc:'Reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.25,gcd:0,cd:90000},
  {id:'divine-hymn',name:'Divine Hymn',kind:'group-heal',role:'healer',spec:'Holy',unlockLevel:1,desc:'A major emergency heal for the entire party.',range:30,heal:32,cost:34,gcd:1500,cast:2600,cd:35000},

  {id:'mind-flay',name:'Mind Flay',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:1,desc:'Channel shadow energy into the target and generate Insanity.',range:35,damage:15,cost:0,gain:12,gcd:1500,cast:1250,cd:0,damageType:'magic'},
  {id:'mind-blast',name:'Mind Blast',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:1,desc:'Assault the target’s mind for heavy shadow damage and Insanity.',range:35,damage:26,cost:0,gain:18,gcd:1500,cast:1200,cd:6500,damageType:'magic'},
  {id:'devouring-plague',name:'Devouring Plague',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:1,desc:'Spend Insanity to infect the target with a powerful devouring shadow plague.',range:35,damage:28,cost:50,gcd:1500,cast:0,cd:0,damageType:'magic'},
  {id:'shadow-word-pain',name:'Shadow Word: Pain',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:4,desc:'Afflict the target with lingering shadow pain while generating Insanity.',range:35,damage:10,cost:0,gain:7,gcd:1500,cast:0,cd:7000,damageType:'magic'},
  {id:'vampiric-touch',name:'Vampiric Touch',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:6,desc:'Apply a draining shadow curse that damages the target over time.',range:35,damage:15,cost:0,gain:10,gcd:1500,cast:1300,cd:11000,damageType:'magic'},
  {id:'shadow-crash',name:'Shadow Crash',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:1,desc:'Crash shadow energy into the target and nearby enemies.',range:35,damage:28,cost:0,gain:12,gcd:1500,cast:800,cd:14000,cleave:3,damageType:'magic'},
  {id:'void-torrent',name:'Void Torrent',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:1,desc:'Channel concentrated Void energy for heavy damage and rapid Insanity generation.',range:35,damage:42,cost:0,gain:28,gcd:1500,cast:1900,cd:30000,damageType:'magic'},
  {id:'void-eruption',name:'Void Eruption',kind:'damage',role:'dps',spec:'Shadow',unlockLevel:1,desc:'Spend Insanity to erupt with Void energy and enter Voidform.',range:35,damage:44,cost:40,gcd:1500,cast:1100,cd:60000,cleave:3,damageType:'magic'},
  {id:'dispersion',name:'Dispersion',kind:'defensive',role:'dps',spec:'Shadow',unlockLevel:8,desc:'Disperse into shadow, greatly reducing incoming damage for 6 seconds.',duration:6000,damageReduction:.40,gcd:0,cd:75000},
  {id:'silence',name:'Silence',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast from range.',range:30,cost:0,gcd:0,cd:30000}
 ],
 Rogue:[
  {id:'mutilate',name:'Mutilate',kind:'damage',role:'dps',spec:'Assassination',unlockLevel:1,desc:'Strike with both weapons and generate two Combo Points.',range:5,damage:24,cost:35,gcd:1000,cd:0,comboGain:2},
  {id:'eviscerate',name:'Eviscerate',kind:'damage',role:'dps',spec:'Assassination',unlockLevel:1,desc:'Spend Combo Points on a hard-hitting finishing attack.',range:5,damage:40,cost:25,gcd:1000,cd:5000,comboCost:4,finisher:true},
  {id:'garrote',name:'Garrote',kind:'damage',role:'dps',spec:'Assassination',unlockLevel:1,desc:'Open a bleeding wound and generate one Combo Point.',range:5,damage:28,cost:30,gcd:1000,cd:7000,comboGain:1},
  {id:'envenom',name:'Envenom',kind:'damage',role:'dps',spec:'Assassination',unlockLevel:5,desc:'Spend Combo Points on a heavy poisoned finisher.',range:5,damage:38,cost:30,gcd:1000,cd:6500,comboCost:4,finisher:true},
  {id:'fan-of-knives',name:'Fan of Knives',kind:'damage',role:'dps',spec:'Assassination',unlockLevel:9,desc:'Strike the target and nearby enemies, generating one Combo Point.',range:8,damage:15,cost:35,gcd:1000,cd:7000,cleave:3,comboGain:1},

  {id:'sinister-strike',name:'Sinister Strike',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:1,desc:'A fast sabre strike that generates one Combo Point.',range:5,damage:21,cost:35,gcd:1000,cd:0,comboGain:1},
  {id:'pistol-shot',name:'Pistol Shot',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:1,desc:'Fire a pistol at short range; Opportunity empowers the shot.',range:18,damage:19,cost:20,gcd:1000,cd:0,comboGain:1},
  {id:'dispatch',name:'Dispatch',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:1,desc:'Spend Combo Points on a powerful melee finisher.',range:5,damage:43,cost:25,gcd:1000,cd:0,comboCost:4,finisher:true},
  {id:'roll-the-bones',name:'Roll the Bones',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:4,desc:'Spend Combo Points to roll a temporary combat advantage.',range:5,damage:8,cost:15,gcd:1000,cd:12000,comboCost:3,finisher:true},
  {id:'blade-flurry',name:'Blade Flurry',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:1,desc:'Enter a cleaving stance that echoes melee damage into nearby enemies.',range:5,damage:18,cost:25,gcd:1000,cd:15000,cleave:2},
  {id:'between-the-eyes',name:'Between the Eyes',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:1,desc:'Spend Combo Points on a pistol finisher that creates a critical-strike window.',range:18,damage:38,cost:25,gcd:1000,cd:18000,comboCost:4,finisher:true},
  {id:'adrenaline-rush',name:'Adrenaline Rush',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:1,desc:'Enter a burst state with greatly increased Energy recovery and attack speed.',range:5,damage:14,cost:0,gcd:1000,cd:60000},
  {id:'killing-spree',name:'Killing Spree',kind:'damage',role:'dps',spec:'Outlaw',unlockLevel:1,desc:'Rapidly strike the target and nearby enemies in a short burst.',range:8,damage:42,cost:35,gcd:1000,cast:800,cd:60000,cleave:2},
  {id:'kick',name:'Kick',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast.',range:5,cost:0,gcd:0,cd:15000},
  {id:'feint',name:'Feint',kind:'defensive',unlockLevel:13,desc:'Reduce incoming damage for 8 seconds.',duration:8000,damageReduction:.20,gcd:0,cd:60000}
 ],
 Shaman:[
  {id:'healing-wave',name:'Healing Wave',kind:'heal',role:'healer',spec:'Restoration',unlockLevel:1,desc:'A dependable restorative cast for an injured ally.',range:30,heal:36,cost:14,gcd:1500,cast:1450,cd:0},
  {id:'riptide',name:'Riptide',kind:'heal',role:'healer',spec:'Restoration',unlockLevel:1,desc:'An instant tidal heal that continues restoring health briefly.',range:30,heal:23,cost:10,gcd:1500,cast:0,cd:6000,hot:7},
  {id:'chain-heal',name:'Chain Heal',kind:'group-heal',role:'healer',spec:'Restoration',unlockLevel:1,desc:'Heal one ally, then bounce restorative energy through other injured party members.',range:30,heal:34,cost:15,gcd:1500,cast:1700,cd:0,chainBounces:3,chainFalloff:.72,chainRange:16},
  {id:'windfury-totem',name:'Windfury Totem',kind:'totem',role:'healer',spec:'Restoration',unlockLevel:1,desc:'Place a Windfury Totem that increases party damage and haste while it remains active.',cost:8,gcd:1000,cd:45000,duration:20000,totemType:'windfury'},
  {id:'stoneskin-totem',name:'Stoneskin Totem',kind:'totem',role:'healer',spec:'Restoration',unlockLevel:1,desc:'Place a Stoneskin Totem that reduces damage taken by the party while it remains active.',cost:10,gcd:1000,cd:45000,duration:20000,totemType:'stoneskin'},
  {id:'healing-stream-totem',name:'Healing Stream Totem',kind:'totem',role:'healer',spec:'Restoration',unlockLevel:1,desc:'Place a Healing Stream Totem that pulses healing through the party while it remains active.',cost:12,gcd:1000,cd:30000,duration:20000,totemType:'healing-stream'},
  {id:'spirit-link-totem',name:'Spirit Link Totem',kind:'totem',role:'healer',spec:'Restoration',unlockLevel:1,desc:'Place an emergency Spirit Link Totem that protects and stabilises injured allies.',cost:18,gcd:1000,cd:75000,duration:8000,totemType:'spirit-link'},
  {id:'restoration-lightning-bolt',name:'Lightning Bolt',kind:'damage',role:'healer',spec:'Restoration',unlockLevel:4,desc:'A ranged lightning attack for safe damage windows.',range:30,damage:13,cost:4,gcd:1500,cast:1200,cd:0,damageType:'magic'},
  {id:'healing-rain',name:'Healing Rain',kind:'group-heal',role:'healer',spec:'Restoration',unlockLevel:8,desc:'Call restorative rain over the party for broad recovery.',range:30,heal:16,cost:24,gcd:1500,cast:1200,cd:10000},

  {id:'lightning-bolt',name:'Lightning Bolt',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:1,desc:'Hurl lightning at the target and generate Maelstrom.',range:35,damage:19,cost:0,gain:12,gcd:1500,cast:1250,cd:0,damageType:'magic'},
  {id:'lava-burst',name:'Lava Burst',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:1,desc:'Launch molten lava for heavy fire damage and generate Maelstrom.',range:35,damage:31,cost:0,gain:16,gcd:1500,cast:1400,cd:8000,damageType:'magic'},
  {id:'earth-shock',name:'Earth Shock',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:1,desc:'Spend Maelstrom to strike the target with a violent earth shock.',range:35,damage:39,cost:60,gcd:1500,cast:0,cd:0,damageType:'magic'},
  {id:'chain-lightning',name:'Chain Lightning',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:4,desc:'Arc lightning through the target and nearby enemies while generating Maelstrom.',range:35,damage:17,cost:0,gain:10,gcd:1500,cast:1350,cd:5000,cleave:3,damageType:'magic'},
  {id:'flame-shock',name:'Flame Shock',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:6,desc:'Burn the target with fire that continues dealing damage and generates Maelstrom.',range:35,damage:12,cost:0,gain:8,gcd:1500,cast:0,cd:8000,damageType:'magic'},
  {id:'earthquake',name:'Earthquake',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:1,desc:'Spend Maelstrom to rupture the ground beneath the enemy pack.',range:35,damage:34,cost:60,gcd:1500,cast:900,cd:6000,cleave:4,damageType:'magic'},
  {id:'stormkeeper',name:'Stormkeeper',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:1,desc:'Call down a storm and enter a short lightning burst window.',range:35,damage:30,cost:0,gain:10,gcd:1500,cast:900,cd:45000,cleave:2,damageType:'magic'},
  {id:'ascendance',name:'Ascendance',kind:'damage',role:'dps',spec:'Elemental',unlockLevel:1,desc:'Become a living storm and unleash a major Elemental burst window.',range:35,damage:42,cost:30,gcd:1500,cast:900,cd:60000,cleave:3,damageType:'magic'},
  {id:'wind-shear',name:'Wind Shear',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast with a sharp burst of wind.',range:30,cost:0,gcd:0,cd:18000},
  {id:'astral-shift',name:'Astral Shift',kind:'defensive',unlockLevel:8,desc:'Shift partially into the spirit world, reducing incoming damage for 8 seconds.',duration:8000,damageReduction:.25,gcd:0,cd:75000}
 ],
 Warlock:[
  {id:'shadow-bolt',name:'Shadow Bolt',kind:'damage',role:'dps',spec:'Demonology',unlockLevel:1,desc:'A reliable ranged shadow spell.',range:35,damage:19,cost:6,gcd:1500,cast:1450,cd:0,damageType:'magic'},
  {id:'demonbolt',name:'Demonbolt',kind:'damage',role:'dps',spec:'Demonology',unlockLevel:1,desc:'Hurl concentrated demonic energy at the target.',range:35,damage:29,cost:11,gcd:1500,cast:1800,cd:6000,damageType:'magic'},
  {id:'hand-of-guldan',name:"Hand of Gul'dan",kind:'damage',role:'dps',spec:'Demonology',unlockLevel:1,desc:'Call down fel energy on the target and nearby enemies.',range:35,damage:23,cost:15,gcd:1500,cast:1500,cd:7000,cleave:2,damageType:'magic'},
  {id:'axe-toss',name:'Axe Toss',kind:'interrupt',role:'dps',spec:'Demonology',unlockLevel:1,desc:'Command your Felguard to hurl its weapon and interrupt an enemy cast.',range:30,cost:0,gcd:0,cd:20000},
  {id:'call-dreadstalkers',name:'Call Dreadstalkers',kind:'summon',role:'dps',spec:'Demonology',unlockLevel:1,desc:'Summon two Dreadstalkers to maul your enemies for a short time.',range:35,cost:16,gcd:1500,cast:1200,cd:20000,duration:12000,summonType:'dreadstalker',summonCount:2},
  {id:'soul-strike',name:'Soul Strike',kind:'pet-command',role:'dps',spec:'Demonology',unlockLevel:1,desc:'Command your Felguard to deliver a crushing soul-infused strike.',range:30,cost:8,gcd:1000,cd:10000,petCommand:'soul-strike',talentReq:'Soul Strike'},
  {id:'felstorm',name:'Felstorm',kind:'pet-command',role:'dps',spec:'Demonology',unlockLevel:1,desc:'Command your Felguard to spin through several nearby enemies.',range:30,cost:12,gcd:1000,cd:18000,petCommand:'felstorm',cleave:3,talentReq:'Felstorm'},
  {id:'implosion',name:'Implosion',kind:'pet-command',role:'dps',spec:'Demonology',unlockLevel:10,desc:'Detonate your temporary demons into the target for explosive area damage.',range:35,cost:10,gcd:1500,cd:16000,petCommand:'implosion',cleave:3},
  {id:'summon-demonic-tyrant',name:'Summon Demonic Tyrant',kind:'summon',role:'dps',spec:'Demonology',unlockLevel:1,desc:'Summon a Demonic Tyrant that bombards enemies and empowers your active demons.',range:35,cost:20,gcd:1500,cast:1600,cd:60000,duration:15000,summonType:'tyrant',summonCount:1,talentReq:'Demonic Tyrant'},

  {id:'incinerate',name:'Incinerate',kind:'damage',role:'dps',spec:'Destruction',unlockLevel:1,desc:'Scorch the target and generate Soul Shards.',range:35,damage:19,cost:0,gain:.5,gcd:1500,cast:1450,cd:0,damageType:'magic',school:'fire'},
  {id:'conflagrate',name:'Conflagrate',kind:'damage',role:'dps',spec:'Destruction',unlockLevel:1,desc:'Instantly blast the target with fire and generate a Soul Shard.',range:35,damage:22,cost:0,gain:1,gcd:1500,cast:0,cd:10000,damageType:'magic',school:'fire'},
  {id:'chaos-bolt',name:'Chaos Bolt',kind:'damage',role:'dps',spec:'Destruction',unlockLevel:1,desc:'Spend Soul Shards on a devastating bolt of chaotic fire.',range:35,damage:48,cost:2,gcd:1500,cast:2100,cd:0,damageType:'magic',school:'chaos'},
  {id:'immolate',name:'Immolate',kind:'damage',role:'dps',spec:'Destruction',unlockLevel:4,desc:'Burn the target over time and generate Soul Shard fragments from the flames.',range:35,damage:11,cost:0,gain:.5,gcd:1500,cast:1200,cd:9000,damageType:'magic',school:'fire'},
  {id:'rain-of-fire',name:'Rain of Fire',kind:'damage',role:'dps',spec:'Destruction',unlockLevel:1,desc:'Spend Soul Shards to rain fire across the enemy pack.',range:35,damage:34,cost:3,gcd:1500,cast:900,cd:7000,cleave:4,damageType:'magic',school:'fire'},
  {id:'channel-demonfire',name:'Channel Demonfire',kind:'damage',role:'dps',spec:'Destruction',unlockLevel:1,desc:'Channel waves of demonfire into burning targets.',range:35,damage:40,cost:0,gain:.5,gcd:1500,cast:1800,cd:24000,cleave:2,damageType:'magic',school:'fire'},
  {id:'summon-infernal',name:'Summon Infernal',kind:'summon',role:'dps',spec:'Destruction',unlockLevel:1,desc:'Crash an Infernal into the enemy pack to burn them for a short time.',range:35,cost:2,gcd:1500,cast:1200,cd:60000,duration:14000,summonType:'infernal',summonCount:1},
  {id:'shadowfury',name:'Shadowfury',kind:'interrupt',role:'dps',spec:'Destruction',unlockLevel:1,desc:'Disrupt an enemy cast with a burst of shadow force.',range:30,cost:0,gcd:0,cd:24000},
  {id:'dark-pact',name:'Dark Pact',kind:'defensive',unlockLevel:8,desc:'Wrap yourself in demonic power, reducing incoming damage for 8 seconds.',duration:8000,damageReduction:.25,gcd:0,cd:75000}
 ],
 Monk:[
  {id:'keg-smash',name:'Keg Smash',kind:'damage',role:'tank',unlockLevel:1,desc:'Smash the target and nearby enemies with heavy threat.',range:8,damage:20,cost:25,gcd:1000,cd:8000,threat:3,cleave:3},
  {id:'brewmaster-blackout-kick',name:'Blackout Kick',kind:'damage',role:'tank',unlockLevel:1,desc:'Reliable Brewmaster melee pressure.',range:5,damage:16,cost:18,gcd:1000,cd:3000,threat:2.2},
  {id:'provoke',name:'Provoke',kind:'taunt',role:'tank',unlockLevel:1,desc:'Challenge an enemy and force its attention onto the Brewmaster.',range:30,cost:0,gcd:0,cd:8000,threat:5},
  {id:'purifying-brew',name:'Purifying Brew',kind:'defensive',role:'tank',unlockLevel:1,desc:'Clear a large portion of accumulated Stagger damage.',duration:1000,damageReduction:0,gcd:0,cd:12000,purifyStagger:.50},
  {id:'celestial-brew',name:'Celestial Brew',kind:'defensive',role:'tank',unlockLevel:6,desc:'Reduce incoming damage while your brews stabilise you.',duration:7000,damageReduction:.28,gcd:0,cd:45000},
  {id:'breath-of-fire',name:'Breath of Fire',kind:'damage',role:'tank',unlockLevel:1,desc:'Breathe fire across the target and nearby enemies.',range:8,damage:18,cost:20,gcd:1000,cd:12000,cleave:3,threat:2.4,damageType:'magic'},
  {id:'fortifying-brew',name:'Fortifying Brew',kind:'defensive',role:'tank',unlockLevel:1,desc:'Major defensive brew that also restores health.',duration:10000,damageReduction:.35,selfHealPct:.15,gcd:0,cd:90000},
  {id:'soothing-mist',name:'Soothing Mist',kind:'heal',role:'healer',unlockLevel:1,desc:'Efficient focused healing through soothing mist.',range:30,heal:29,cost:10,gcd:1500,cast:950,cd:0},
  {id:'vivify',name:'Vivify',kind:'heal',role:'healer',unlockLevel:1,desc:'A strong direct heal for an injured ally.',range:30,heal:35,cost:15,gcd:1500,cast:1250,cd:0},
  {id:'renewing-mist',name:'Renewing Mist',kind:'heal',role:'healer',unlockLevel:1,desc:'Instant healing that continues restoring the target over time.',range:30,heal:20,cost:11,gcd:1500,cast:0,cd:6000,hot:7},
  {id:'essence-font',name:'Essence Font',kind:'group-heal',role:'healer',unlockLevel:6,desc:'Release a wave of healing across the party.',range:30,heal:16,cost:23,gcd:1500,cast:1500,cd:9000},
  {id:'mist-rising-sun-kick',name:'Rising Sun Kick',kind:'damage',role:'healer',unlockLevel:4,desc:'A martial strike that can fuel fistweaving healing.',range:5,damage:19,cost:5,gcd:1000,cd:8000},
  {id:'mist-tiger-palm',name:'Tiger Palm',kind:'damage',role:'healer',unlockLevel:4,desc:'A quick martial strike for safe healing windows.',range:5,damage:11,cost:2,gcd:1000,cd:0},
  {id:'revival',name:'Revival',kind:'group-heal',role:'healer',unlockLevel:1,desc:'Instantly restore the whole party in an emergency.',range:30,heal:32,cost:30,gcd:1500,cast:0,cd:45000},
  {id:'tiger-palm',name:'Tiger Palm',kind:'damage',role:'dps',unlockLevel:1,desc:'A quick strike that maintains martial pressure.',range:5,damage:14,cost:18,gain:10,gcd:1000,cd:0},
  {id:'windwalker-blackout-kick',name:'Blackout Kick',kind:'damage',role:'dps',unlockLevel:1,desc:'A fast finishing kick in the Windwalker rotation.',range:5,damage:20,cost:26,gcd:1000,cd:3000},
  {id:'windwalker-rising-sun-kick',name:'Rising Sun Kick',kind:'damage',role:'dps',unlockLevel:1,desc:'A heavy martial strike with a short cooldown.',range:5,damage:31,cost:32,gcd:1000,cd:8000},
  {id:'spinning-crane-kick',name:'Spinning Crane Kick',kind:'damage',role:'dps',unlockLevel:5,desc:'Spin through the target and nearby enemies.',range:7,damage:17,cost:28,gcd:1000,cd:7000,cleave:3},
  {id:'fists-of-fury',name:'Fists of Fury',kind:'damage',role:'dps',unlockLevel:1,desc:'Unleash a powerful flurry that cleaves nearby enemies.',range:6,damage:34,cost:38,gcd:1000,cast:1300,cd:18000,cleave:2},
  {id:'touch-of-death',name:'Touch of Death',kind:'damage',role:'dps',unlockLevel:1,desc:'A devastating finishing technique against weakened enemies.',range:5,damage:30,cost:20,gcd:1000,cd:30000,executeBelow:.20,executeMultiplier:2.4},
  {id:'touch-of-karma',name:'Touch of Karma',kind:'defensive',role:'dps',unlockLevel:9,desc:'Reduce incoming damage for a short period.',duration:7000,damageReduction:.25,gcd:0,cd:75000},
  {id:'spear-hand-strike',name:'Spear Hand Strike',kind:'interrupt',unlockLevel:1,desc:'Interrupt an enemy cast with a precise hand strike.',range:5,cost:0,gcd:0,cd:15000}
 ]
};

const ROLE_FALLBACKS={
 tank:[
  {id:'guard-strike',name:'Guard Strike',kind:'damage',range:5,damage:18,cost:0,gcd:1500,cd:0,threat:2.6},
  {id:'provoke',name:'Provoke',kind:'taunt',range:30,cost:0,gcd:0,cd:8000,threat:5}
 ],
 healer:[
  {id:'restore',name:'Restore',kind:'heal',range:30,heal:31,cost:10,gcd:1500,cast:1000,cd:0},
  {id:'renewing-wave',name:'Renewing Wave',kind:'group-heal',range:30,heal:14,cost:18,gcd:1500,cast:1200,cd:8000},
  {id:'light-bolt',name:'Light Bolt',kind:'damage',range:30,damage:11,cost:3,gcd:1500,cast:900,cd:0}
 ],
 dps:[
  {id:'strike',name:'Strike',kind:'damage',range:5,damage:18,cost:0,gcd:1500,cd:0},
  {id:'interrupt',name:'Interrupt',kind:'interrupt',range:10,cost:0,gcd:0,cd:18000}
 ]
};

const TALENT_SKILL_REQUIREMENTS={
  'mortal-strike':'Mortal Strike','overpower':'Overpower','sweeping-strike':'Sweeping Blows',
  'consecration':'Consecration','ardent-defender':'Ardent Defender','holy-shock':'Holy Shock','radiant-wave':'Radiance',
  'guardian-spirit':'Guardian Spirit','divine-hymn':'Divine Hymn',
  'wild-growth':'Wild Growth','tranquility':'Tranquility','starfall':'Starfall','fury-of-elune':'Fury of Elune','celestial-alignment':'Celestial Alignment',
  'kill-shot':'Kill Shot','dire-beast':'Dire Beast','stampede':'Stampede','bestial-wrath':'Bestial Wrath','garrote':'Garrote','envenom':'Envenom','blade-flurry':'Blade Flurry','between-the-eyes':'Between the Eyes','adrenaline-rush':'Adrenaline Rush','killing-spree':'Killing Spree','arcane-barrage':'Barrage','blizzard':'Blizzard','frozen-orb':'Frozen Orb','glacial-spike':'Glacial Spike',
  'spirit-link-totem':'Spirit Link Totem','earthquake':'Earthquake','stormkeeper':'Stormkeeper','ascendance':'Ascendance','soul-strike':'Soul Strike','felstorm':'Felstorm','summon-demonic-tyrant':'Demonic Tyrant','rain-of-fire':'Rain of Fire','channel-demonfire':'Channel Demonfire','summon-infernal':'Summon Infernal',
  'breath-of-fire':'Breath of Fire','fortifying-brew':'Fortifying Brew','revival':'Revival','fists-of-fury':'Fists of Fury','touch-of-death':'Touch of Death',
  'rune-tap':'Rune Tap','dancing-rune-weapon':'Dancing Rune Weapon','vampiric-blood':'Vampiric Blood','remorseless-winter':'Remorseless Winter','breath-of-sindragosa':'Breath of Sindragosa','dark-transformation':'Dark Transformation','army-of-the-dead':'Army of the Dead','apocalypse':'Apocalypse',
  'fel-barrage':'Fel Barrage','havoc-metamorphosis':'Metamorphosis','sigil-of-flame':'Sigil of Flame','spirit-bomb':'Spirit Bomb','vengeance-metamorphosis':'Metamorphosis',
  'dream-breath':'Dream Breath','emerald-communion':'Emerald Communion','eternity-surge':'Eternity Surge','dragonrage':'Dragonrage',
  'shadow-crash':'Shadow Crash','void-torrent':'Void Torrent','void-eruption':'Void Eruption'
};

const TALENT_RULES={
 'Shield Mastery':'More block chance and physical mitigation per rank.',
 'Last Stand':'Once per encounter, falling dangerously low restores health and grants brief protection.',
 'Iron Discipline':'Reduces physical damage taken.',
 'Taunt Mastery':'Taunts hold enemies longer and create a larger threat lead.',
 'Hold the Line':'Blocking grants a short damage-reduction buff.',
 'Vengeance':'Taking damage briefly increases outgoing damage.',
 'Bulwark':'Using a major defensive also protects the party.',
 'Fortress':'Reduces damage taken during boss encounters.',
 'Unbroken':'Once per encounter, a lethal hit leaves the Warrior standing at 1 HP.',
 'Weapon Mastery':'Increases weapon damage.',
 'Deep Wounds':'Critical weapon hits cause a real damage-over-time bleed.',
 'Battle Rhythm':'Successful attacks build a short damage and haste buff.',
 'Overpower':'Deals extra damage to casting or recently interrupted enemies.',
 'Sweeping Blows':'Single-target attacks splash damage to another enemy.',
 'Executioner':'Increases damage against low-health enemies.',
 'Mortal Strike':'Unlocks Mortal Strike and makes it hit harder.',
 'Blood Frenzy':'Bleeding a target grants haste.',
 'Bladestorm':'Against groups, periodically unleashes a real party-visible area attack.',
 'Sacred Shield':'Increases block and physical mitigation.',
 'Guardian Oath':'Increases threat and reduces damage taken.',
 'Righteous Guard':'Blocking grants additional short mitigation.',
 'Hammer of Justice':'Improves interrupt recovery and briefly controls non-boss enemies.',
 'Consecration':'Unlocks Consecration and improves its damage and group threat.',
 'Divine Ward':'Reduces magical damage taken.',
 'Ardent Defender':'Unlocks and strengthens Ardent Defender.',
 'Holy Bastion':'Increases block during boss encounters.',
 'Divine Guardian':'A major defensive also grants party-wide protection.',
 'Divine Light':'Increases direct healing.',
 'Grace':'Reduces mana costs of healing skills.',
 'Holy Shock':'Unlocks Holy Shock and increases its healing.',
 'Infusion':'Direct heals can trigger a short haste buff.',
 'Beacon':'Single-target healing echoes onto the tank.',
 'Sacred Hands':'Heals low-health allies for more.',
 'Aura Mastery':'Makes Blessing of Resolve stronger and last longer.',
 'Radiance':'Unlocks Radiant Wave and causes direct heals to splash to nearby allies.',
 'Divine Hymn':'Empowers major party healing.',
 'Renew':'Direct heals leave a real healing-over-time effect.',
 'Serenity':'Increases direct healing.',
 'Prayer of Mending':'Direct heals jump to additional injured allies.',
 'Focused Will':'Reduces damage taken while the Priest is under pressure.',
 'Circle of Healing':'Increases party-wide healing.',
 'Spirit of Redemption':'On defeat, releases a final heal across surviving allies.',
 'Guardian Spirit':'Unlocks Guardian Spirit and can prevent a lethal hit on an ally.',
 'Divine Insight':'Direct heals can echo for extra healing.',
 'Rejuvenation':'Improves Rejuvenation and its healing-over-time ticks.',
 'Lifebloom':'Focused healing plants additional healing ticks.',
 'Wild Growth':'Unlocks Wild Growth and improves party healing.',
 'Natural Swiftness':'Periodically makes a casted heal instant.',
 'Living Seed':'Direct healing can plant a delayed heal.',
 'Ironbark':'Automatically protects a critically injured ally on a cooldown.',
 'Tree of Life':'Under heavy pressure, temporarily boosts healing and haste.',
 'Flourish':'Party heals extend restoration with an additional healing pulse.',
 'Tranquility':'Unlocks and strengthens Tranquility.',
 'Starlight':'Increases Wrath and Starfire damage and Astral Power generation.',
 'Twin Moons':'Increases Moonfire and Sunfire periodic damage.',
 "Nature's Balance":'Further improves Astral Power generation and helps maintain Eclipse cycles.',
 'Shooting Stars':'Periodic Balance damage can generate extra Astral Power.',
 'Starfall':'Unlocks Starfall as an equipable area Astral Power spender.',
 'Soul of the Forest':'Strengthens the matching spell-school bonus granted by Solar and Lunar Eclipse.',
 'Fury of Elune':'Unlocks Fury of Elune, an astral beam that damages packs and generates Astral Power.',
 'Astral Communion':'Empowers Astral Power spenders and periodically refunds Astral Power.',
 'Celestial Alignment':'Unlocks Celestial Alignment, empowering Solar and Lunar magic simultaneously.',
 'True Aim':'Increases ranged damage.',
 'Rapid Fire':'Reduces Hunter ability cooldowns.',
 'Steady Focus':'Increases damage while the Hunter is stationary.',
 'Concussive Shot':'Damaging attacks can briefly control non-boss enemies.',
 'Piercing Shots':'Critical shots cause a bleed.',
 'Trueshot Aura':'Increases party ranged damage.',
 'Careful Aim':'Deals extra damage to healthy enemies.',
 'Killer Instinct':'Deals extra damage to weakened enemies.',
 'Kill Shot':'Unlocks Kill Shot and improves its execute threshold and damage.',
 'Pack Leader':'Increases damage dealt by the permanent beast and temporary beasts.',
 'Killer Cobra':'Increases Cobra Shot damage and improves Focus efficiency.',
 'Barbed Wrath':'Barbed Shot grants a stronger and longer Frenzy to the permanent beast.',
 'Wild Call':'Kill Command helps recover Barbed Shot.',
 'Dire Beast':'Unlocks Dire Beast, a temporary beast summon that generates Focus.',
 'Beast Cleave':'Multi-Shot causes the permanent beast to cleave nearby enemies.',
 'Stampede':'Unlocks Stampede, calling several beasts into the fight.',
 'Thrill of the Hunt':'Pet commands grant a short critical-strike and haste surge.',
 'Bestial Wrath':'Unlocks Bestial Wrath, empowering both hunter and permanent beast.',
 'Ambush':'Increases opening damage.',
 'Venom':'Adds poison damage to attacks.',
 'Garrote':'Unlocks Garrote and strengthens its bleed.',
 'Quick Recovery':'Increases Energy regeneration.',
 'Mutilate':'Strengthens Mutilate.',
 'Envenom':'Unlocks and strengthens Envenom.',
 'Master Poisoner':'Improves poison damage.',
 'Cut to the Chase':'Envenom grants a short haste buff.',
 'Eviscerate':'Strengthens Eviscerate as a finisher.',
 'Opportunity':'Sinister Strike builds toward an empowered Pistol Shot.',
 'Combat Potency':'Increases Outlaw Energy regeneration.',
 'Quick Draw':'Opportunity-empowered Pistol Shot deals more damage and generates extra Combo Points.',
 'Ruthlessness':'Spending Combo Points accelerates key Outlaw cooldowns.',
 'Blade Flurry':'Unlocks Blade Flurry, allowing melee attacks to echo into nearby enemies.',
 'Between the Eyes':'Unlocks a ranged Combo Point finisher that creates a critical-strike window.',
 'Adrenaline Rush':'Unlocks and strengthens a major Energy and haste burst window.',
 'Loaded Dice':'Roll the Bones grants stronger combat advantages.',
 'Killing Spree':'Unlocks Killing Spree, a rapid sequence of weapon strikes.',
 'Arcane Focus':'Increases spell damage.',
 'Surge':'Repeated spell hits can trigger a short damage surge.',
 'Clearcasting':'Spells can cost no Mana.',
 'Spell Impact':'Increases spell critical damage.',
 'Presence of Mind':'Periodically makes a casted spell instant.',
 'Arcane Flows':'Reduces Mage cooldowns.',
 'Arcane Power':'Automatically triggers a major damage cooldown in difficult combat.',
 'Nether Precision':'Increases spell critical chance.',
 'Barrage':'Unlocks Arcane Barrage and makes it hit harder with splash damage.',
 'Piercing Cold':'Increases Frostbolt, Flurry and Ice Lance damage.',
 'Ice Shards':'Increases Frost spell critical chance.',
 'Fingers of Frost':'Frostbolt and Blizzard build toward an empowered Ice Lance.',
 'Brain Freeze':'Frostbolt can make Flurry instant and prepare Winter’s Chill.',
 'Blizzard':'Unlocks Blizzard as an equipable area frost spell.',
 'Shatter':'Greatly increases Ice Lance and Glacial Spike damage during frozen-state windows.',
 'Frozen Orb':'Unlocks Frozen Orb, which deals repeated frost damage through enemy packs.',
 'Thermal Void':'Consuming Frost procs grants a short haste and damage surge.',
 'Glacial Spike':'Unlocks Glacial Spike, a devastating Frost capstone finisher.',
 'Tidal Focus':'Increases Restoration healing and reduces the Mana cost of healing spells.',
 'Totemic Mastery':'Makes equipped Shaman totems stronger and keeps them active longer.',
 'Riptide':'Strengthens Riptide and its lingering healing.',
 'Ancestral Reach':'Extends Chain Heal bounce range and improves later jumps.',
 'Chain Mastery':'Reduces the healing lost as Chain Heal jumps between allies.',
 'Earthen Ward':'Strengthens Stoneskin Totem and Spirit Link protection.',
 'Tidal Waves':'Riptide and Chain Heal grant a short haste buff for follow-up healing.',
 'Spirit Link Totem':'Unlocks Spirit Link Totem as an equipable combat skill for dangerous party pressure.',
 'Ascendant Tide':'Under heavy pressure, empowers Restoration healing and briefly surges the active totem network.',
 'Elemental Fury':'Increases Lightning Bolt, Chain Lightning and Lava Burst damage.',
 'Flame Shock':'Increases the periodic damage of Flame Shock.',
 'Lava Surge':'Flame Shock ticks can reset Lava Burst and accelerate its next cast.',
 'Elemental Equilibrium':'Alternating fire and nature damage grants a short damage surge.',
 'Aftershock':'Earth Shock and Earthquake can refund Maelstrom.',
 'Earthquake':'Unlocks Earthquake as an equipable area Maelstrom spender.',
 'Master of the Elements':'Lava Burst empowers the next nature spell.',
 'Stormkeeper':'Unlocks Stormkeeper, creating a short lightning burst window.',
 'Ascendance':'Unlocks Ascendance, creating a major Elemental burst window.',
 'Demonic Bond':'Increases damage dealt by the Felguard and all temporary demons.',
 'Fel Knowledge':'Increases the damage of Warlock shadow and fel spells.',
 'Soul Strike':'Unlocks Soul Strike, an equipable command for the permanent Felguard.',
 'Dread Calling':'Increases Dreadstalker damage and duration.',
 'Pack Tactics':'Increases demon attack speed.',
 'Felstorm':'Unlocks Felstorm, an equipable Felguard area command.',
 'Demonic Core':'Demon attacks can trigger a short damage and haste surge for the Warlock.',
 'Master Summoner':'Extends temporary demon duration and reduces summon cooldowns.',
 'Demonic Tyrant':'Unlocks Summon Demonic Tyrant, a powerful temporary ranged demon.',
 'Eradication':'Chaos Bolt leaves the target vulnerable to follow-up Destruction damage.',
 'Roaring Blaze':'Increases Immolate and Conflagrate damage.',
 'Backdraft':'Conflagrate reduces the cast time of the next casted Destruction spell.',
 'Reverse Entropy':'Soul Shard spenders periodically grant a short haste surge.',
 'Rain of Fire':'Unlocks Rain of Fire as an equipable area Soul Shard spender.',
 'Havoc':'Chaos Bolt and Incinerate can echo damage into a second nearby enemy.',
 'Channel Demonfire':'Unlocks Channel Demonfire, rewarding targets already burning from Immolate.',
 'Soul Conduit':'Soul Shard spenders periodically refund Soul Shards.',
 'Summon Infernal':'Unlocks Summon Infernal, a major temporary demon for Destruction.',
 'High Tolerance':'Increases the share of incoming physical damage delayed by Stagger.',
 'Elusive Brawler':'Reduces damage taken while Brewmaster is under pressure.',
 'Purifying Brew':'Purifying Brew removes more accumulated Stagger per rank.',
 'Keg Mastery':'Increases Keg Smash damage and threat.',
 'Gift of the Ox':'Taking sustained damage can trigger a small self-heal.',
 'Breath of Fire':'Unlocks Breath of Fire and improves pack pressure.',
 'Celestial Brew':'Strengthens Celestial Brew, especially while Stagger is high.',
 'Shuffle':'Reduces each periodic Stagger damage release.',
 'Fortifying Brew':'Unlocks a major defensive brew with health recovery.',
 'Mist Wrap':'Increases Mistweaver direct healing.',
 'Lifecycles':'Reduces Mana costs when alternating healing techniques.',
 'Renewing Mist':'Improves Renewing Mist and its healing-over-time ticks.',
 'Ancient Teachings':'Martial damage smart-heals the most injured ally.',
 'Enveloping Breath':'Direct Mistweaver healing splashes onto nearby injured allies.',
 'Jade Serpent':'Healing casts can trigger a small additional jade-serpent heal.',
 'Rising Mist':'Improves healing generated by Mistweaver martial attacks.',
 'Mana Tea':'Improves Mana efficiency and regeneration.',
 'Revival':'Unlocks Revival, an instant emergency party heal.',
 'Combo Strikes':'Windwalker deals more damage when rotating different attacks and less when repeating one.',
 'Ferocity':'Increases Windwalker martial damage.',
 'Rising Sun Kick':'Increases Rising Sun Kick damage.',
 'Dance of the Wind':'Improves personal mitigation.',
 'Fists of Fury':'Unlocks Fists of Fury.',
 'Jade Ignition':'Area martial attacks deal additional cleave damage.',
 'Momentum':'Successful Combo Strikes grant a short haste surge.',
 'Serenity':'Reduces Windwalker ability costs and cooldowns.',
 'Touch of Death':'Unlocks a powerful execute against weakened enemies.',
 'Heartbreaker':'Improves Heart Strike damage, threat and Runic Power generation.',
 'Ossuary':'Marrowrend grants a stronger Bone Shield.',
 'Hemostasis':'Blood Boil empowers the next Death Strike.',
 'Rune Tap':'Unlocks Rune Tap as an equipable short defensive cooldown.',
 'Blood Shield':'Death Strike grants a short protective blood shield.',
 'Voracious':'Increases Death Strike healing from recent damage.',
 'Dancing Rune Weapon':'Unlocks a major defensive window that also improves threat.',
 'Red Thirst':'Reduces Blood defensive cooldowns.',
 'Vampiric Blood':'Unlocks Vampiric Blood, restoring health and improving incoming healing.',
 'Killing Machine':'Increases critical chance for Obliterate and frost finishers.',
 'Icy Talons':'Frost Strike grants a short haste buff.',
 'Rime':'Improves Howling Blast damage and Runic Power generation.',
 'Obliteration':'Increases Obliterate damage.',
 'Runic Empowerment':'Runic Power spenders can restore Runic Power.',
 'Remorseless Winter':'Unlocks Remorseless Winter for sustained frost cleave.',
 'Avalanche':'Critical frost attacks splash extra damage.',
 'Frozen Pulse':'Low Runic Power strengthens generator attacks.',
 'Breath of Sindragosa':'Unlocks a powerful frost cleave finisher.',
 'Festering Wounds':'Festering Strike applies more wounds and wound bursts deal more damage.',
 'Dark Transformation':'Strengthens the permanent Ghoul and unlocks its transformation command.',
 'Infected Claws':'Ghoul attacks can add disease pressure.',
 'Epidemic':'Disease ticks splash damage to nearby enemies.',
 'Sudden Doom':'Ghoul attacks can empower Death Coil.',
 'Army of the Dead':'Unlocks Army of the Dead as an equipable undead summon.',
 'Unholy Pact':'You and your undead deal more damage while temporary undead are active.',
 'Defile':'Strengthens Death and Decay and plague pressure.',
 'Apocalypse':'Unlocks Apocalypse, consuming wounds and summoning additional undead.',
 'Demon Blades':"Increases Havoc core strike damage and improves Demon's Bite Fury generation.",
 'Furious Gaze':'Eye Beam grants a short haste surge.',
 'Initiative':'Increases Havoc opening damage.',
 'Soul Rending':'Heavy Havoc fel attacks restore a portion of damage dealt as health.',
 'First Blood':'Increases Blade Dance damage and cleave pressure.',
 'Fel Barrage':'Unlocks Fel Barrage as an equipable Havoc area skill.',
 'Demonic':'Eye Beam briefly grants a demonic damage surge.',
 'Chaos Theory':'Strengthens Chaos Strike and gives it a chance to refund Fury.',
 'Thick Skin':'Reduces physical and magical damage taken by Vengeance.',
 'Soul Cleave':'Increases healing from Soul Cleave and consumed Soul Fragments.',
 'Fracture':'Shear generates extra Fury and can create an additional Soul Fragment.',
 'Sigil of Flame':'Unlocks Sigil of Flame as an equipable Vengeance area-threat skill.',
 'Feed the Demon':'Reduces Vengeance defensive cooldowns.',
 'Spirit Bomb':'Unlocks Spirit Bomb, consuming Soul Fragments for area damage and healing.',
 'Soul Barrier':'Consuming Soul Fragments grants short additional mitigation.',
 'Fiery Demise':'Increases Vengeance fel and fire damage.',
 'Metamorphosis':'Unlocks the active Metamorphosis skill for the current Demon Hunter specialisation.',
 'Temporal Mending':'Increases direct Preservation healing.',
 'Essence Attunement':'Improves Preservation Essence regeneration.',
 'Reversion':'Improves Reversion and its healing-over-time ticks.',
 'Lifebind':'Verdant Embrace echoes healing onto another injured ally.',
 'Echoing Bloom':'Emerald Blossom leaves an additional delayed healing pulse.',
 'Dream Breath':'Unlocks Dream Breath as an equipable Preservation group heal.',
 'Time Lord':'Reduces Preservation healing cooldowns.',
 'Cycle of Life':'Group heals can trigger a delayed restorative pulse across the party.',
 'Emerald Communion':'Unlocks Emerald Communion as a major emergency party heal.',
 'Dragonfire':'Increases Devastation red-dragon spell damage.',
 'Azure Mastery':'Increases Devastation blue-dragon spell damage and cleave.',
 'Essence Burst':'Living Flame and Azure Strike can make the next Essence spender free.',
 'Burnout':'Fire Breath empowers the next Living Flame.',
 'Eternity Surge':'Unlocks Eternity Surge as a heavy blue-dragon burst spell.',
 'Pyre':'Increases Pyre damage and area pressure.',
 'Scintillation':'Disintegrate can trigger an extra burst of blue magic.',
 'Power Swell':'Spending Essence grants a short haste surge.',
 'Dragonrage':'Unlocks Dragonrage, a major Devastation burst window.',
 'Dark Thoughts':'Strengthens Mind Flay and Mind Blast and increases the Insanity generated by Mind Flay.',
 'Shadow Weaving':'Increases damage from Shadow Word: Pain, Vampiric Touch and Devouring Plague.',
 'Mind Devourer':'Mind Blast can make the next Devouring Plague free.',
 'Vampiric Embrace':'Lingering Shadow damage restores a portion of the Priest’s health.',
 'Shadow Crash':'Unlocks Shadow Crash as an equipable ranged cleave skill.',
 'Twist of Fate':'Increases Shadow damage against enemies below 35% health.',
 'Psychic Link':'Mind Blast and Devouring Plague splash damage into another nearby enemy.',
 'Void Torrent':'Unlocks Void Torrent, a heavy channel that generates a large amount of Insanity.',
 'Void Eruption':'Unlocks Void Eruption and grants a short Voidform burst window.'
};

window.CellboundCombatData=Object.freeze({
  version:'1.0.0',
  CLASS_COLORS,RESOURCE_DEFS,CLASS_BUFFS,ABILITIES,ROLE_FALLBACKS,TALENT_SKILL_REQUIREMENTS,TALENT_RULES
});
})();
