const SUPABASE_URL='https://jvydqeikdpelmtloulnd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_R79iqkCPo4hRgXNNzzTmAg_ODAiA1fl';
const REMEMBER_KEY='cellbound-remember-device';
const email=document.getElementById('email'),password=document.getElementById('password'),form=document.getElementById('login-form'),message=document.getElementById('login-message'),intro=document.getElementById('login-intro'),remember=document.getElementById('remember-device'),enter=document.getElementById('enter-button'),create=document.getElementById('create-account'),forgot=document.getElementById('forgot-password'),toggle=document.getElementById('toggle-password');
const authStorage={getItem:k=>localStorage.getItem(k)??sessionStorage.getItem(k),setItem(k,v){const keep=localStorage.getItem(REMEMBER_KEY)==='1';const a=keep?localStorage:sessionStorage,b=keep?sessionStorage:localStorage;a.setItem(k,v);b.removeItem(k)},removeItem(k){localStorage.removeItem(k);sessionStorage.removeItem(k)}};
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:authStorage}});
let recovery=false,routing=false;
function msg(text,tone='info'){message.hidden=false;message.dataset.tone=tone;message.textContent=text}function busy(on){enter.disabled=on;create.disabled=on;forgot.disabled=on;enter.querySelector('span').textContent=on?'CONNECTING…':'ENTER GUILD COMMAND'}
function creds(requirePass=true){const e=email.value.trim(),p=password.value;if(!e||!email.validity.valid){msg('Enter a valid email address.','error');return null}if(requirePass&&p.length<6){msg('Your password must be at least 6 characters.','error');return null}return{email:e,password:p}}
async function profile(user){if(!user?.id)return;await sb.from('profiles').upsert({user_id:user.id},{onConflict:'user_id'})}
function enterGame(user){if(routing||recovery)return;routing=true;msg(`Welcome back${user?.email?`, ${user.email}`:''}. Opening Guild Command…`,'success');busy(true);setTimeout(()=>location.replace('./guild.html'),300)}
function friendly(error){const m=error?.message||'Something went wrong.';if(/invalid login credentials/i.test(m))return'Email or password is incorrect.';if(/email not confirmed/i.test(m))return'Confirm your email before entering Cellbound.';if(/already registered/i.test(m))return'That email already has a Cellbound account.';return m}
toggle?.addEventListener('click',()=>{const show=password.type==='text';password.type=show?'password':'text';toggle.textContent=show?'Show':'Hide'});
remember.checked=localStorage.getItem(REMEMBER_KEY)==='1';remember.addEventListener('change',()=>localStorage.setItem(REMEMBER_KEY,remember.checked?'1':'0'));
form.addEventListener('submit',async e=>{e.preventDefault();if(recovery){if(password.value.length<6)return msg('Your new password must be at least 6 characters.','error');busy(true);const{error}=await sb.auth.updateUser({password:password.value});busy(false);if(error)return msg(friendly(error),'error');recovery=false;intro.textContent='Sign in to continue your guild.';return msg('Password updated.','success')}const c=creds();if(!c)return;localStorage.setItem(REMEMBER_KEY,remember.checked?'1':'0');busy(true);const{data,error}=await sb.auth.signInWithPassword(c);if(error){busy(false);return msg(friendly(error),'error')}await profile(data.user);enterGame(data.user)});
create.addEventListener('click',async()=>{const c=creds();if(!c)return;busy(true);const{data,error}=await sb.auth.signUp(c);if(error){busy(false);return msg(friendly(error),'error')}if(data.session&&data.user){await profile(data.user);return enterGame(data.user)}busy(false);msg('Account created. Confirm the email, then sign in.','success')});
forgot.addEventListener('click',async()=>{const c=creds(false);if(!c)return;busy(true);const{error}=await sb.auth.resetPasswordForEmail(c.email);busy(false);msg(error?friendly(error):'Password reset email sent.',error?'error':'success')});
sb.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recovery=true;routing=false;intro.textContent='Choose a new password.';password.value='';password.autocomplete='new-password';enter.querySelector('span').textContent='SET NEW PASSWORD';msg('Recovery link accepted.','info');return}if(event==='SIGNED_IN'&&session?.user&&!recovery)enterGame(session.user)});
(async()=>{const{data}=await sb.auth.getSession();if(data.session?.user&&!recovery){await profile(data.session.user);enterGame(data.session.user)}})();