(()=>{
'use strict';
const SUPABASE_URL='https://jvydqeikdpelmtloulnd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_R79iqkCPo4hRgXNNzzTmAg_ODAiA1fl';
const REMEMBER_KEY='cellbound-remember-device';
const authStorage={getItem:k=>localStorage.getItem(k)??sessionStorage.getItem(k),setItem(k,v){const remember=localStorage.getItem(REMEMBER_KEY)==='1';const a=remember?localStorage:sessionStorage,b=remember?sessionStorage:localStorage;a.setItem(k,v);b.removeItem(k)},removeItem(k){localStorage.removeItem(k);sessionStorage.removeItem(k)}};
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:authStorage}});
const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const ui={playerName:$('playerName'),level:$('level'),hpFill:$('hpFill'),hpText:$('hpText'),focusFill:$('focusFill'),bossHud:$('bossHud'),bossFill:$('bossFill'),bossPct:$('bossPct'),bossState:$('bossState'),miniTitle:$('miniTitle'),miniState:$('miniState'),miniObjective:$('miniObjective'),questTitle:$('questTitle'),questText:$('questText'),chatLog:$('chatLog'),toast:$('toast'),basicBtn:$('basicBtn'),basicIcon:$('basicIcon'),slamBtn:$('slamBtn'),slamLabel:$('slamLabel'),slamCooldown:$('slamCooldown'),inventoryBtn:$('inventoryBtn'),cellsBtn:$('cellsBtn'),joy:$('joy'),knob:$('knob'),action:$('action'),actionIcon:$('actionIcon'),actionLabel:$('actionLabel'),prompt:$('prompt'),dialog:$('dialog'),dialogName:$('dialogName'),dialogText:$('dialogText'),dialogPortrait:$('dialogPortrait'),next:$('next'),inventoryPanel:$('inventoryPanel'),inventoryGrid:$('inventoryGrid'),itemDetail:$('itemDetail'),cellsPanel:$('cellsPanel'),cellList:$('cellList'),absorbBtn:$('absorbBtn'),deathPanel:$('deathPanel'),retryBtn:$('retryBtn'),completionPanel:$('completionPanel'),completionBtn:$('completionBtn'),loading:$('loading'),loadingText:$('loadingText')};
const PIX=3;let vw=0,vh=0,last=performance.now(),elapsed=0,mode='town',dialogueQueue=[],dialogueIndex=0,paused=true,attackCd=0,slamCd=0,trollCd=0,trollState='idle',trollTimer=0,shake=0,flash=0,joyPointer=null,joyVec={x:0,y:0},toastTimer=0,autosaveTimer=0,dummyHit=0;
const world={w:1100,h:800};
const player={x:550,y:650,hp:100,max:100,speed:112,name:'Bound One',style:'melee',level:1,walk:0,face:0,characterId:null,userId:null,appearance:{},tutorialStage:'arrived_curo',tutorialComplete:false,rewardClaimed:false};
const mage={x:610,y:400};const shopkeeper={x:292,y:315};const gatekeeper={x:550,y:225};
const troll={x:550,y:260,hp:620,max:620,on:false,dead:false,hit:0};const dummy={x:720,y:390,hp:42,max:42,active:false,dead:false};const portal={x:550,y:595,active:false};
const camera={x:0,y:0};const keys=new Set();
let inventory=[],cells=[],abilities=[],quests=[];
const buildings=[{x:150,y:150,w:190,h:132,name:'CURO GOODS',roof:'#9c5542'},{x:760,y:155,w:190,h:135,name:'SUNLIT CUP',roof:'#8f493e'},{x:125,y:500,w:170,h:115,name:'COTTAGE',roof:'#6d5141'},{x:815,y:505,w:160,h:112,name:'HOME',roof:'#80503f'},{x:455,y:54,w:205,h:120,name:'OLD HALL',roof:'#58604a'}];
const townTrees=[[64,80],[94,245],[60,690],[245,720],[985,82],[1015,240],[1025,650],[858,700],[352,88],[744,84],[357,690],[742,690],[385,570],[720,570],[388,250],[710,250]];
const mageIntro=["There you are. I've been waiting for you.","Curo is peaceful, but the world beyond it is not.","Power here isn't simply learned. Some creatures carry something rarer: Cells.","Defeat something powerful enough and you may claim the Cell it leaves behind.","Come. There is something beneath Curo you need to see."];
const dungeonIntro=["This chamber has been sealed beneath Curo for longer than anyone remembers.","Remember what I told you. Powerful creatures are the path to Cells.","And sometimes... they find you first."];
const cellDialogue=["That's a Cell.","Creatures like Gorvak don't surrender their power easily. But now it's yours.","Open your Cells and absorb it. Then show me what it gave you."];
const finalDialogue=["You understand now.","The creatures beyond Curo are stronger than anything you've seen here. So are the Cells they carry.","What you become from here is up to you."];
const postDialogue=["The first Cell is already changing the way you carry yourself.","Keep your eyes open beyond Curo. Power rarely announces itself twice."];
function resize(){vw=Math.ceil(innerWidth/PIX);vh=Math.ceil(innerHeight/PIX);canvas.width=vw;canvas.height=vh;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),sx=x=>Math.round(x-camera.x),sy=y=>Math.round(y-camera.y);
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function px(x,y,c,s=1){rect(x,y,s,s,c)}function shadow(x,y,w,h){ctx.fillStyle='#0006';ctx.fillRect(Math.round(x-w/2),Math.round(y),Math.round(w),Math.round(h))}
function log(message,tone=''){const d=document.createElement('div');d.className=tone;d.innerHTML=message;ui.chatLog.appendChild(d);while(ui.chatLog.children.length>8)ui.chatLog.removeChild(ui.chatLog.firstChild);ui.chatLog.scrollTop=ui.chatLog.scrollHeight}
function toast(message,ms=2200){ui.toast.textContent=message;ui.toast.hidden=false;toastTimer=ms/1000}
function setQuest(title,text){ui.questTitle.textContent=title;ui.questText.textContent=text}
function setAction(label,icon='✦',prompt=''){ui.actionLabel.textContent=label;ui.actionIcon.textContent=icon;ui.prompt.textContent=prompt;ui.prompt.hidden=!prompt}
function updateHUD(){ui.playerName.textContent=player.name.toUpperCase();ui.level.textContent=player.level;ui.hpFill.style.width=`${clamp(player.hp/player.max*100,0,100)}%`;ui.hpText.textContent=`${Math.ceil(player.hp)} / ${player.max}`;ui.bossFill.style.width=`${clamp(troll.hp/troll.max*100,0,100)}%`;ui.bossPct.textContent=`${Math.ceil(clamp(troll.hp/troll.max*100,0,100))}%`;const hasSlam=abilities.some(a=>a.ability_key==='troll_slam');ui.slamBtn.disabled=!hasSlam;ui.slamBtn.classList.toggle('locked',!hasSlam);ui.slamLabel.textContent=hasSlam?(slamCd>0?`${slamCd.toFixed(1)}s`:'SLAM'):'LOCKED';ui.slamCooldown.style.height=hasSlam&&slamCd>0?`${clamp(slamCd/6*100,0,100)}%`:'0%';ui.focusFill.style.width=hasSlam?'100%':'0%'}
async function saveCharacter(fields={}){if(!player.characterId)return;const payload={last_played_at:new Date().toISOString(),updated_at:new Date().toISOString(),...fields};const {error}=await supabaseClient.from('characters').update(payload).eq('id',player.characterId).eq('user_id',player.userId);if(error)console.warn('Character save failed',error.message)}
async function saveStage(stage,extra={}){player.tutorialStage=stage;await saveCharacter({tutorial_stage:stage,current_location:mode,...extra})}
async function loadPersistentState(){const {data:session,error:sessionError}=await supabaseClient.auth.getSession();if(sessionError||!session.session?.user){location.replace('./index.html');return false}player.userId=session.session.user.id;const {data:char,error}=await supabaseClient.from('characters').select('id,name,combat_style,appearance,level,current_hp,max_hp,current_location,tutorial_stage,tutorial_complete,tutorial_reward_claimed,creation_complete').eq('user_id',player.userId).order('created_at',{ascending:true}).limit(1).maybeSingle();if(error||!char?.creation_complete){location.replace('./character.html');return false}player.characterId=char.id;player.name=char.name||player.name;player.style=char.combat_style||player.style;player.appearance=char.appearance||{};player.level=char.level||1;player.max=char.max_hp||100;player.hp=clamp(char.current_hp??player.max,1,player.max);player.tutorialStage=char.tutorial_stage||'arrived_curo';player.tutorialComplete=!!char.tutorial_complete;player.rewardClaimed=!!char.tutorial_reward_claimed;const [invRes,cellRes,abilityRes,questRes]=await Promise.all([supabaseClient.from('inventory_items').select('*').eq('character_id',player.characterId).order('created_at'),supabaseClient.from('character_cells').select('*').eq('character_id',player.characterId).order('acquired_at'),supabaseClient.from('character_abilities').select('*').eq('character_id',player.characterId).order('hotbar_slot'),supabaseClient.from('quest_progress').select('*').eq('character_id',player.characterId).order('created_at')]);inventory=invRes.data||[];cells=cellRes.data||[];abilities=abilityRes.data||[];quests=questRes.data||[];return true}
function renderInventory(){ui.inventoryGrid.innerHTML='';const starter=[{item_key:'starter_blade',item_name:player.style==='magic'?'Apprentice Focus':player.style==='ranged'?'Ash Shortbow':'Curo Blade',item_type:'weapon',quantity:1,rarity:'common',metadata:{description:'Your first reliable weapon.'}}];const all=[...starter,...inventory];all.forEach(item=>{const b=document.createElement('button');b.className=`inv-item ${item.rarity==='rare'?'rare':''}`;const icon=item.item_type==='cell'?'◇':item.item_type==='material'?'☠':'⚔';b.innerHTML=`<span>${icon}</span><b>${item.item_name}</b><small>${item.quantity>1?`×${item.quantity} · `:''}${item.rarity||'common'}</small>`;b.addEventListener('click',()=>{ui.itemDetail.innerHTML=`<b>${item.item_name}</b><p>${item.metadata?.description||'A recovered item from your journey.'}</p>`});ui.inventoryGrid.appendChild(b)});if(!all.length)ui.inventoryGrid.innerHTML='<p>Your pack is empty.</p>'}
function renderCells(){ui.cellList.innerHTML='';if(!cells.length){ui.cellList.innerHTML='<div class="cell-card"><small>NO CELLS BOUND</small><h3>Unknown</h3><p>Powerful creatures may leave Cells behind.</p></div>';ui.absorbBtn.hidden=true;return}cells.forEach(cell=>{const d=document.createElement('div');d.className='cell-card';d.innerHTML=`<small>${cell.absorbed?'ABSORBED':'UNBOUND CELL'}</small><h3>◇ ${cell.cell_name}</h3><p>${cell.description}</p>`;ui.cellList.appendChild(d)});const unbound=cells.find(c=>c.cell_key==='troll_cell'&&!c.absorbed);ui.absorbBtn.hidden=!unbound}
function openPanel(panel){panel.hidden=false;paused=true;if(panel===ui.inventoryPanel)renderInventory();if(panel===ui.cellsPanel)renderCells()}
function closePanels(){ui.inventoryPanel.hidden=true;ui.cellsPanel.hidden=true;if(ui.dialog.hidden&&ui.deathPanel.hidden&&ui.completionPanel.hidden)paused=false}
function beginDialogue(name,portrait,lines,onDone){dialogueQueue=lines.map(text=>({name,portrait,text}));dialogueIndex=0;ui.dialog.hidden=false;paused=true;ui.next.onclick=()=>advanceDialogue(onDone);showDialogueLine()}
function showDialogueLine(){const line=dialogueQueue[dialogueIndex];ui.dialogName.textContent=line.name;ui.dialogPortrait.textContent=line.portrait;ui.dialogText.textContent=line.text;ui.next.textContent=dialogueIndex===dialogueQueue.length-1?'CONTINUE →':'NEXT →'}
function advanceDialogue(onDone){dialogueIndex++;if(dialogueIndex>=dialogueQueue.length){ui.dialog.hidden=true;paused=false;onDone?.();return}showDialogueLine()}
function configureFromStage(){const stage=player.tutorialStage;if(player.tutorialComplete||stage==='complete'){mode='town';player.x=550;player.y=650;troll.on=false;portal.active=false;ui.miniTitle.textContent='Curo';ui.miniState.textContent='SAFE';const q=quests.find(q=>q.quest_key==='world_beyond_curo'&&q.status==='active');setQuest(q?.quest_title||'A World Beyond Curo',q?.data?.objective||'Speak with the Gatekeeper at Curo’s northern road.');log(`Welcome back to <span class="gold">Curo</span>.`);return}
if(['dungeon_entered','troll_active','troll_defeated','loot_collected','cell_absorbed','ability_used','return_ready'].includes(stage)){mode='dungeon';player.x=550;player.y=575;ui.miniTitle.textContent='Forgotten Hollow';ui.miniState.textContent='DANGER';if(stage==='dungeon_entered'){startTroll(false)}else if(stage==='troll_active'){startTroll(false)}else if(stage==='troll_defeated'){troll.dead=true;troll.on=true;troll.hp=0;setQuest('Claim What Remains','Loot Gorvak’s remains.')}else if(stage==='loot_collected'){troll.dead=true;troll.on=true;troll.hp=0;setQuest('Your First Cell','Open Cells and absorb the Troll Cell.')}else if(stage==='cell_absorbed'){troll.dead=true;dummy.active=true;setQuest('Power Made Yours','Use Troll Slam on the training effigy.')}else if(stage==='ability_used'||stage==='return_ready'){troll.dead=true;dummy.dead=true;portal.active=true;setQuest('Return to Curo','Enter the portal and return to the Mage.')}}else{mode='town';player.x=550;player.y=650;setQuest('The Waiting Mage','Find the mage beside Curo’s old well.')}}
function drawGrass(){rect(0,0,vw,vh,'#273d2d');for(let y=-8;y<vh+8;y+=8)for(let x=-8;x<vw+8;x+=8){const wx=x+camera.x,wy=y+camera.y,n=((Math.floor(wx/8)*17+Math.floor(wy/8)*31)%7+7)%7;rect(x,y,8,8,n<2?'#315039':n<4?'#2b4632':'#29422f');if(n===0){px(x+2,y+5,'#4d7147');px(x+4,y+3,'#577d4d')}}}
function drawPath(){ctx.save();ctx.translate(-camera.x,-camera.y);ctx.fillStyle='#766b53';ctx.fillRect(505,0,90,800);ctx.fillRect(0,350,1100,90);ctx.fillStyle='#395938';ctx.beginPath();ctx.ellipse(550,395,115,90,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawBuilding(b){const x=sx(b.x),y=sy(b.y);shadow(x+b.w/2,y+b.h-2,b.w+18,12);rect(x,y+24,b.w,b.h-24,'#b69d70');rect(x+8,y+30,b.w-16,b.h-35,'#c2aa7a');ctx.fillStyle=b.roof;ctx.beginPath();ctx.moveTo(x-12,y+30);ctx.lineTo(x+b.w/2,y-18);ctx.lineTo(x+b.w+12,y+30);ctx.lineTo(x+b.w-5,y+49);ctx.lineTo(x+5,y+49);ctx.closePath();ctx.fill();rect(x+b.w*.43,y+b.h-42,28,42,'#5e4634');rect(x+24,y+63,28,28,'#56767b');rect(x+b.w-52,y+63,28,28,'#56767b');if(b.name==='CURO GOODS'){rect(x+47,y+b.h-5,96,22,'#503825');ctx.fillStyle='#ecd89e';ctx.font='7px monospace';ctx.textAlign='center';ctx.fillText('CURO GOODS',x+95,y+b.h+8)}}
function tree(wx,wy,s=1.1){const x=sx(wx),y=sy(wy);shadow(x,y+14,28*s,6);rect(x-3*s,y,6*s,18*s,'#60472f');const cs=['#274f31','#2e6338','#397441','#24482d'];for(let i=0;i<7;i++){ctx.fillStyle=cs[i%cs.length];ctx.fillRect(Math.round(x+((i%3)-1)*8*s),Math.round(y-12*s+Math.floor(i/3)*7*s),Math.round(15*s),Math.round(13*s))}}
function well(){const x=sx(550),y=sy(395);shadow(x,y+17,70,9);rect(x-33,y-10,66,24,'#7c7767');rect(x-28,y-8,56,18,'#aaa28c');rect(x-22,y-7,44,13,'#31565d');rect(x-30,y-35,5,30,'#765d43');rect(x+25,y-35,5,30,'#765d43');rect(x-34,y-38,68,5,'#765d43');rect(x-4,y-37,8,16,'#4c3828')}
function drawNpc(n,kind='mage'){const x=sx(n.x),y=sy(n.y);shadow(x,y+12,21,5);if(kind==='mage'){rect(x-9,y-7,18,25,'#223a43');rect(x-12,y+6,24,14,'#1a2b32');rect(x-7,y-20,14,12,'#c5a17b');rect(x-8,y-23,16,5,'#324c53');rect(x+10,y-25,3,37,'#765331');rect(x+8,y-27,7,7,'#52dbe0');px(x+10,y-25,'#d4ffff',2)}else{rect(x-7,y-8,14,22,kind==='gate'?'#4c3c2f':'#56412f');rect(x-6,y-19,12,11,'#c9a17d');rect(x-8,y-21,16,4,kind==='gate'?'#30373a':'#6b4a2d')}if(kind==='mage'&&!player.tutorialComplete){ctx.fillStyle='#60e6ee';ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText('!',x,y-31)}}
function drawPlayer(){const x=sx(player.x),y=sy(player.y)+(player.walk?Math.sin(elapsed*15):0);shadow(x,y+12,20,5);rect(x-7,y-8,14,21,'#2a3236');rect(x-9,y+8,7,11,'#1b2326');rect(x+2,y+8,7,11,'#1b2326');rect(x-6,y-19,12,11,player.appearance.skin||'#d1a07c');rect(x-7,y-21,14,5,player.appearance.hairColor||'#2d2725');rect(x-11,y-7,4,16,'#7a2b29');if(player.style==='ranged'){ctx.strokeStyle='#b38b58';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+12,y-4,7,-1.2,1.2);ctx.stroke()}else if(player.style==='magic'){rect(x+10,y-6,2,18,'#6b5138');rect(x+8,y-10,6,6,'#53d7e4')}else{rect(x+9,y-9,2,19,'#b6c1c0');rect(x+7,y+7,6,2,'#76583a')}if(flash>0){ctx.strokeStyle='#efd07b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,18+flash*35,-1.2,1.25);ctx.stroke()}}
function drawTown(){drawGrass();drawPath();townTrees.forEach(t=>tree(t[0],t[1]));buildings.forEach(drawBuilding);for(let i=0;i<54;i++){const wx=40+(i*137)%1020,wy=55+(i*211)%700;if(Math.hypot(wx-550,wy-395)<150)continue;px(sx(wx),sy(wy),['#e1d777','#d58d91','#8fbcc8','#d7d9c8'][i%4])}well();drawNpc(mage,'mage');drawNpc(shopkeeper,'shop');drawNpc(gatekeeper,'gate')}
function stoneFloor(){rect(0,0,vw,vh,'#0e1516');ctx.save();ctx.translate(-camera.x,-camera.y);rect(145,100,810,590,'#1c2525');for(let y=112;y<680;y+=18)for(let x=155;x<945;x+=26){const c=((x+y)/2)%3?'#2b3432':'#252e2d';ctx.fillStyle=c;ctx.fillRect(x+(Math.floor(y/18)%2?10:0),y,23,15);ctx.fillStyle='#121918';ctx.fillRect(x+(Math.floor(y/18)%2?10:0),y+14,23,2)}for(let i=0;i<10;i++){const a=i*Math.PI*2/10,cx=550+Math.cos(a)*250,cy=390+Math.sin(a)*170;rect(cx-10,cy-18,20,36,'#34403d');rect(cx-8,cy-28,16,10,'#6a4d34');rect(cx-4,cy-35,8,9,'#e58d3b');rect(cx-2,cy-34,4,5,'#ffd16b')}ctx.strokeStyle='#3d4c49';ctx.lineWidth=2;ctx.beginPath();ctx.arc(550,390,150,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawTroll(){const x=sx(troll.x),y=sy(troll.y);shadow(x,y+26,50,8);const hit=troll.hit>0;rect(x-18,y-10,36,36,hit?'#a8c886':'#58784b');rect(x-25,y,11,31,hit?'#93b875':'#4c6943');rect(x+14,y,11,31,hit?'#93b875':'#4c6943');rect(x-14,y+24,11,20,'#38462f');rect(x+3,y+24,11,20,'#38462f');rect(x-15,y-30,30,22,hit?'#b7d493':'#6e905a');rect(x-11,y-35,8,7,'#3a432e');rect(x+5,y-35,8,7,'#3a432e');px(x-8,y-20,'#e5d77c',3);px(x+6,y-20,'#e5d77c',3);rect(x+23,y-20,5,48,'#765538');rect(x+20,y-23,19,9,'#59412e');if(trollState==='smash'){ctx.strokeStyle='#cf554c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,30+trollTimer*18,0,Math.PI*2);ctx.stroke()}}
function drawLoot(){if(!troll.dead)return;const x=sx(550),y=sy(300);ctx.fillStyle='#e9dec5';ctx.font='15px monospace';ctx.fillText('☠',x-23,y+5);ctx.fillStyle='#60e6ef';ctx.font='23px monospace';ctx.fillText('◇',x+16,y+5);ctx.fillStyle='#59dfe944';ctx.fillRect(x+10,y-10,18,18)}
function drawDummy(){if(!dummy.active||dummy.dead)return;const x=sx(dummy.x),y=sy(dummy.y);shadow(x,y+15,28,6);rect(x-4,y-2,8,32,'#6c5338');rect(x-19,y+4,38,6,'#7c6041');rect(x-12,y-18,24,18,'#8b6d49');ctx.fillStyle='#d3b36e';ctx.font='7px monospace';ctx.textAlign='center';ctx.fillText('EFFIGY',x,y-24)}
function drawPortal(){if(!portal.active)return;const x=sx(portal.x),y=sy(portal.y);const r=22+Math.sin(elapsed*4)*3;ctx.strokeStyle='#5ddfe8';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y,r,r*1.5,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#4fdde522';ctx.beginPath();ctx.ellipse(x,y,r-5,(r-5)*1.45,0,0,Math.PI*2);ctx.fill()}
function drawDungeon(){stoneFloor();if(troll.on&&!troll.dead)drawTroll();drawLoot();drawDummy();drawPortal();drawNpc({x:380,y:560},'mage')}
function draw(){ctx.clearRect(0,0,vw,vh);ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*4,(Math.random()-.5)*4);mode==='town'?drawTown():drawDungeon();drawPlayer();ctx.restore()}
function canMove(nx,ny){if(nx<22||ny<22||nx>world.w-22||ny>world.h-22)return false;if(mode==='town'){for(const b of buildings)if(nx>b.x-18&&nx<b.x+b.w+18&&ny>b.y-32&&ny<b.y+b.h+12)return false;if(Math.hypot(nx-550,ny-395)<48)return false}else if(nx<165||nx>935||ny<120||ny>665)return false;return true}
function movement(){let x=0,y=0;if(keys.has('w')||keys.has('arrowup'))y--;if(keys.has('s')||keys.has('arrowdown'))y++;if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;x+=joyVec.x;y+=joyVec.y;const len=Math.hypot(x,y);return len>1?{x:x/len,y:y/len}:{x,y}}
function nearestContext(){if(mode==='town'){const dm=dist(player,mage),ds=dist(player,shopkeeper),dg=dist(player,gatekeeper);if(dm<62)return{type:'mage',distance:dm};if(ds<58)return{type:'shop',distance:ds};if(dg<60)return{type:'gate',distance:dg};return null}if(troll.on&&!troll.dead)return{type:'troll',distance:dist(player,troll)};if(troll.dead&&player.tutorialStage==='troll_defeated'&&Math.hypot(player.x-550,player.y-300)<70)return{type:'loot'};if(dummy.active&&!dummy.dead&&dist(player,dummy)<95)return{type:'dummy'};if(portal.active&&dist(player,portal)<70)return{type:'portal'};return null}
function updateContext(){const c=nearestContext();if(!c){setAction('INTERACT','✦','');return}if(c.type==='mage')setAction('TALK','✦','Speak to the Mage');else if(c.type==='shop')setAction('TALK','▣','Speak to the shopkeeper');else if(c.type==='gate')setAction('TALK','⌂','Speak to the Gatekeeper');else if(c.type==='troll')setAction('ATTACK',player.style==='magic'?'✦':player.style==='ranged'?'➶':'⚔',c.distance<90?'Attack Gorvak':'Move closer to Gorvak');else if(c.type==='loot')setAction('LOOT','◇','Loot Gorvak’s remains');else if(c.type==='dummy')setAction('SLAM','◇','Use Troll Slam');else if(c.type==='portal')setAction('RETURN','✦','Return to Curo')}
function updateTroll(dt){if(!troll.on||troll.dead||paused)return;troll.hit=Math.max(0,troll.hit-dt);trollCd=Math.max(0,trollCd-dt);const d=dist(player,troll);if(trollState==='smash'){trollTimer-=dt;ui.bossState.textContent='HEAVY SMASH — MOVE!';if(trollTimer<=0){if(d<92)damagePlayer(20);trollState='recover';trollTimer=1.1;shake=.25}return}if(trollState==='roar'){trollTimer-=dt;ui.bossState.textContent='GORVAK ROARS — ATTACK WINDOW';if(trollTimer<=0){trollState='idle';trollCd=1}return}if(trollState==='recover'){trollTimer-=dt;ui.bossState.textContent='RECOVERING';if(trollTimer<=0){trollState='idle';trollCd=1.3}return}ui.bossState.textContent='CELL-BEARER · TUTORIAL BOSS';if(d>58){const dx=(player.x-troll.x)/d,dy=(player.y-troll.y)/d;troll.x+=dx*34*dt;troll.y+=dy*34*dt}if(trollCd<=0){const r=Math.random();if(r<.24){trollState='smash';trollTimer=1.15;trollCd=5}else if(r<.38){trollState='roar';trollTimer=1.8;trollCd=5}else if(d<65){damagePlayer(10);trollCd=1.45}else trollCd=.45}}
function damagePlayer(amount){player.hp=Math.max(0,player.hp-amount);shake=.18;updateHUD();if(player.hp<=0)playerDeath()}
async function playerDeath(){paused=true;ui.deathPanel.hidden=false;await saveCharacter({current_hp:0,tutorial_stage:'troll_active',current_location:'dungeon'})}
function startTroll(save=true){mode='dungeon';troll.on=true;troll.dead=false;troll.hp=troll.max;troll.x=550;troll.y=255;trollState='idle';trollCd=1.2;player.hp=player.max;player.x=550;player.y=585;portal.active=false;dummy.active=false;ui.bossHud.hidden=false;ui.miniTitle.textContent='Forgotten Hollow';ui.miniState.textContent='DANGER';setQuest('The Cell-Bearer','Defeat Gorvak, the Curo Troll.');log('Gorvak crashes into the chamber.','red');if(save)saveStage('troll_active',{current_hp:player.hp,current_location:'dungeon'});updateHUD()}
function attack(){if(paused||attackCd>0)return;attackCd=.62;flash=.22;const target=troll.on&&!troll.dead?troll:null;if(target&&dist(player,target)<90){const damage=player.style==='magic'?14:player.style==='ranged'?13:15;target.hp=Math.max(0,target.hp-damage);target.hit=.16;shake=.05;if(target.hp<=0)defeatTroll()}else toast('No target in range.',900);updateHUD()}
async function defeatTroll(){troll.dead=true;troll.hp=0;trollState='dead';ui.bossHud.hidden=true;setQuest('Claim What Remains','Loot Gorvak’s remains.');log('Gorvak has fallen. Something unusual is glowing beside the remains.','gold');toast('GORVAK DEFEATED',2400);await saveStage('troll_defeated',{current_hp:player.hp,current_location:'dungeon'})}
async function claimLoot(){paused=true;ui.loading.classList.remove('hide');ui.loadingText.textContent='Claiming Gorvak’s remains...';const {data,error}=await supabaseClient.rpc('claim_tutorial_troll_reward',{p_character_id:player.characterId});if(error){console.error(error);ui.loading.classList.add('hide');paused=false;toast('Could not claim the loot. Try again.');return}if(data===false&&!player.rewardClaimed){await loadPersistentState()}else{player.rewardClaimed=true;const [invRes,cellRes]=await Promise.all([supabaseClient.from('inventory_items').select('*').eq('character_id',player.characterId),supabaseClient.from('character_cells').select('*').eq('character_id',player.characterId)]);inventory=invRes.data||[];cells=cellRes.data||[]}player.tutorialStage='loot_collected';ui.loading.classList.add('hide');paused=false;renderInventory();renderCells();toast('Troll Bones + Troll Cell added to your inventory.',3000);log('<span class="cyan">Troll Cell</span> added to your collection.');setQuest('Your First Cell','Open Cells and absorb the Troll Cell.');beginDialogue('THE MAGE','✦',cellDialogue,()=>openPanel(ui.cellsPanel))}
async function absorbCell(){ui.absorbBtn.disabled=true;ui.absorbBtn.textContent='BINDING…';const {data,error}=await supabaseClient.rpc('absorb_tutorial_troll_cell',{p_character_id:player.characterId});ui.absorbBtn.disabled=false;ui.absorbBtn.textContent='ABSORB CELL';if(error||data===false){toast('The Cell would not bind. Try again.');return}const [invRes,cellRes,abilityRes]=await Promise.all([supabaseClient.from('inventory_items').select('*').eq('character_id',player.characterId),supabaseClient.from('character_cells').select('*').eq('character_id',player.characterId),supabaseClient.from('character_abilities').select('*').eq('character_id',player.characterId)]);inventory=invRes.data||[];cells=cellRes.data||[];abilities=abilityRes.data||[];player.tutorialStage='cell_absorbed';closePanels();dummy.active=true;dummy.dead=false;dummy.hp=dummy.max;setQuest('Power Made Yours','Use Troll Slam on the training effigy.');toast('NEW ABILITY — TROLL SLAM',3000);log('The <span class="cyan">Troll Cell</span> unlocks <span class="gold">Troll Slam</span>.');updateHUD()}
async function useSlam(){if(paused||slamCd>0||!abilities.some(a=>a.ability_key==='troll_slam'))return;slamCd=6;shake=.22;const validDummy=dummy.active&&!dummy.dead&&dist(player,dummy)<100;if(validDummy){dummy.hp=0;dummy.dead=true;dummyHit=.35;portal.active=true;player.tutorialStage='return_ready';setQuest('Return to Curo','Enter the portal and return to the Mage.');toast('TROLL SLAM',1300);log('The effigy splinters under your new Cell ability.','gold');await saveStage('return_ready',{current_location:'dungeon'});return}const validTroll=troll.on&&!troll.dead&&dist(player,troll)<100;if(validTroll){troll.hp=Math.max(0,troll.hp-42);troll.hit=.18;if(troll.hp<=0)await defeatTroll();updateHUD();return}toast('Move closer to your target.',1000)}
async function enterDungeon(){paused=true;toast('Entering Forgotten Hollow…',1500);await saveStage('dungeon_entered',{current_location:'dungeon'});setTimeout(()=>{mode='dungeon';player.x=550;player.y=585;ui.miniTitle.textContent='Forgotten Hollow';ui.miniState.textContent='DANGER';setQuest('Something Below','Listen to the Mage.');beginDialogue('THE MAGE','✦',dungeonIntro,()=>startTroll(true))},650)}
async function returnToCuro(){paused=true;toast('Returning to Curo…',1300);mode='town';player.x=550;player.y=650;portal.active=false;troll.on=false;ui.bossHud.hidden=true;ui.miniTitle.textContent='Curo';ui.miniState.textContent='SAFE';await saveStage('returned_curo',{current_location:'curo',current_hp:player.max});player.hp=player.max;setTimeout(()=>beginDialogue('THE MAGE','✦',finalDialogue,completeTutorial),500)}
async function completeTutorial(){paused=true;const {data,error}=await supabaseClient.rpc('complete_cellbound_tutorial',{p_character_id:player.characterId});if(error||data===false){paused=false;toast('Progress could not be saved. Speak to the Mage again.');return}player.tutorialComplete=true;player.tutorialStage='complete';const qRes=await supabaseClient.from('quest_progress').select('*').eq('character_id',player.characterId);quests=qRes.data||[];const q=quests.find(q=>q.quest_key==='world_beyond_curo');setQuest(q?.quest_title||'A World Beyond Curo',q?.data?.objective||'Speak with the Gatekeeper at Curo’s northern road.');ui.completionPanel.hidden=false;log('Tutorial complete. <span class="gold">A World Beyond Curo</span> is now active.');updateHUD()}
function interact(){if(paused)return;const c=nearestContext();if(!c){toast('Nothing to interact with nearby.',900);return}if(c.type==='mage'){if(player.tutorialComplete){beginDialogue('THE MAGE','✦',postDialogue);return}if(player.tutorialStage==='arrived_curo'||player.tutorialStage==='mage_met'||!player.tutorialStage){saveStage('mage_met',{current_location:'town'});beginDialogue('THE MAGE','✦',mageIntro,enterDungeon);return}if(player.tutorialStage==='returned_curo'){beginDialogue('THE MAGE','✦',finalDialogue,completeTutorial);return}beginDialogue('THE MAGE','✦',["Finish what we started. The Cell won't wait forever."])}else if(c.type==='shop')beginDialogue('MIRA · CURO GOODS','▣',["You look new. Keep whatever Gorvak drops — even the ugly bits.","Come back after you've seen what the Mage wants to show you."]);else if(c.type==='gate'){beginDialogue('GATEKEEPER RENN','⌂',player.tutorialComplete?["The northern road is yours when you're ready.","Curo is safe. Don't expect the same beyond the gate."]:["The northern road stays closed until the Mage says you're ready."])}else if(c.type==='troll')attack();else if(c.type==='loot')claimLoot();else if(c.type==='dummy')useSlam();else if(c.type==='portal')returnToCuro()}
function update(dt){elapsed+=dt;attackCd=Math.max(0,attackCd-dt);slamCd=Math.max(0,slamCd-dt);flash=Math.max(0,flash-dt);shake=Math.max(0,shake-dt*2.5);dummyHit=Math.max(0,dummyHit-dt);if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)ui.toast.hidden=true}if(paused){updateHUD();return}const mv=movement();const moving=Math.hypot(mv.x,mv.y)>.05;if(moving){player.walk=1;player.face=Math.atan2(mv.y,mv.x);const nx=player.x+mv.x*player.speed*dt,ny=player.y+mv.y*player.speed*dt;if(canMove(nx,player.y))player.x=nx;if(canMove(player.x,ny))player.y=ny}else player.walk=0;updateTroll(dt);updateContext();const targetX=player.x-vw/2,targetY=player.y-vh/2;camera.x+=(clamp(targetX,0,Math.max(0,world.w-vw))-camera.x)*Math.min(1,dt*7);camera.y+=(clamp(targetY,0,Math.max(0,world.h-vh))-camera.y)*Math.min(1,dt*7);autosaveTimer+=dt;if(autosaveTimer>12){autosaveTimer=0;saveCharacter({current_hp:Math.ceil(player.hp),current_location:mode})}updateHUD()}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','1','2','i','c'].includes(k))e.preventDefault();keys.add(k);if(k==='1'||k===' ')attack();if(k==='2')useSlam();if(k==='i')ui.inventoryPanel.hidden?openPanel(ui.inventoryPanel):closePanels();if(k==='c')ui.cellsPanel.hidden?openPanel(ui.cellsPanel):closePanels();if(k==='escape')closePanels()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function setJoy(e){const r=ui.joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,len=Math.hypot(dx,dy),max=r.width*.32,scale=len>max?max/len:1,pxv=dx*scale,pyv=dy*scale;ui.knob.style.transform=`translate(${pxv}px,${pyv}px)`;joyVec.x=clamp(dx/max,-1,1);joyVec.y=clamp(dy/max,-1,1)}ui.joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;ui.joy.setPointerCapture(e.pointerId);setJoy(e)});ui.joy.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)setJoy(e)});function clearJoy(e){if(e.pointerId!==joyPointer)return;joyPointer=null;joyVec={x:0,y:0};ui.knob.style.transform='translate(0,0)'}ui.joy.addEventListener('pointerup',clearJoy);ui.joy.addEventListener('pointercancel',clearJoy);
ui.action.addEventListener('click',interact);ui.basicBtn.addEventListener('click',attack);ui.slamBtn.addEventListener('click',useSlam);ui.inventoryBtn.addEventListener('click',()=>openPanel(ui.inventoryPanel));ui.cellsBtn.addEventListener('click',()=>openPanel(ui.cellsPanel));ui.absorbBtn.addEventListener('click',absorbCell);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closePanels));ui.retryBtn.addEventListener('click',async()=>{ui.deathPanel.hidden=true;player.hp=player.max;paused=false;startTroll(true)});ui.completionBtn.addEventListener('click',()=>{ui.completionPanel.hidden=true;paused=false;toast('A World Beyond Curo is now active.',2500)});
(async()=>{try{const ok=await loadPersistentState();if(!ok)return;configureFromStage();renderInventory();renderCells();updateHUD();ui.loadingText.textContent='Curo is ready.';setTimeout(()=>{ui.loading.classList.add('hide');paused=false;log(`You arrive in <span class="gold">${mode==='town'?'Curo':'Forgotten Hollow'}</span>.`);if(player.tutorialStage==='arrived_curo')toast('Use the movement control or WASD to explore.',2500)},350);requestAnimationFrame(loop)}catch(err){console.error(err);ui.loadingText.textContent='The world could not be loaded. Refresh to try again.'}})();
})();
