(()=>{
'use strict';
const SUPABASE_URL='https://jvydqeikdpelmtloulnd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_R79iqkCPo4hRgXNNzzTmAg_ODAiA1fl';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORAGE='cellbound-management-reboot-v1';
const pageTitle=$('#pageTitle'),rosterGrid=$('#rosterGrid'),overviewRoster=$('#overviewRoster'),partyRoster=$('#partyRoster'),partySlots=$('#partySlots'),readinessFill=$('#readinessFill'),readinessText=$('#readinessText'),readinessLabel=$('#readinessLabel'),readinessHint=$('#readinessHint'),bossSelect=$('#bossSelect'),attemptBtn=$('#attemptBtn'),bossList=$('#bossList'),reportsList=$('#reportsList'),activityLog=$('#activityLog'),characterModal=$('#characterModal'),characterDetail=$('#characterDetail'),attemptModal=$('#attemptModal'),attemptStage=$('#attemptStage'),renownEl=$('#renown'),goldEl=$('#gold'),rosterCount=$('#rosterCount'),dungeonProgress=$('#dungeonProgress');
const classes={
  Bulwark:{role:'tank',icon:'🛡',glow:'#5599cc'},Templar:{role:'tank',icon:'✥',glow:'#80a5d8'},
  Lifebinder:{role:'healer',icon:'✚',glow:'#69c98c'},Oracle:{role:'healer',icon:'✦',glow:'#7fd5a1'},
  Spellblade:{role:'dps',icon:'⚔',glow:'#d36e68'},Ranger:{role:'dps',icon:'➶',glow:'#c59b62'},Arcanist:{role:'dps',icon:'✧',glow:'#9879df'},Reaver:{role:'dps',icon:'◆',glow:'#d17857'}
};
const bosses=[
 {id:'ashwarden',name:'Ash Warden Kael',rune:'♜',glow:'#8c4e35',recommended:42,mechanic:'Tank pressure and frontal cleave.',loot:['Warden’s Iron Visor','Cinderbound Shield','Ashen Signet']},
 {id:'embermaw',name:'Embermaw',rune:'♨',glow:'#b66232',recommended:56,mechanic:'Heavy group damage and interrupt checks.',loot:['Emberhide Boots','Scorched Longbow','Heartcoal Charm']},
 {id:'vaultheart',name:'The Vaultheart',rune:'◇',glow:'#805b98',recommended:68,mechanic:'Multi-phase encounter with burst windows.',loot:['Vaultheart Core','Runic Greatblade','Crown of the Deep Forge']}
];
const starterRoster=[
 {id:'r1',name:'Thane Alder',class:'Bulwark',level:6,power:48,gear:46,talent:1,knowledge:{ashwarden:18,embermaw:0,vaultheart:0},portrait:'TA',gearItems:['Ironbound Helm','Tempered Chestplate','Dwarven Shield'],talents:{Fortress:2,Resolve:1,Command:0}},
 {id:'r2',name:'Mira Voss',class:'Lifebinder',level:6,power:45,gear:43,talent:1,knowledge:{ashwarden:12,embermaw:0,vaultheart:0},portrait:'MV',gearItems:['Willow Hood','Acolyte Robe','Mender’s Staff'],talents:{Renewal:2,Clarity:1,Sanctuary:0}},
 {id:'r3',name:'Kael Renn',class:'Spellblade',level:6,power:52,gear:49,talent:1,knowledge:{ashwarden:22,embermaw:0,vaultheart:0},portrait:'KR',gearItems:['Steel Visor','Ashcloak','Runed Longsword'],talents:{Tempo:2,Precision:1,Overcharge:0}},
 {id:'r4',name:'Sera Vale',class:'Ranger',level:5,power:44,gear:42,talent:1,knowledge:{ashwarden:9,embermaw:0,vaultheart:0},portrait:'SV',gearItems:['Tracker Hood','Worn Jerkin','Yew Bow'],talents:{Focus:2,Volley:1,Expose:0}},
 {id:'r5',name:'Orin Pell',class:'Arcanist',level:5,power:46,gear:44,talent:1,knowledge:{ashwarden:14,embermaw:0,vaultheart:0},portrait:'OP',gearItems:['Sage Circlet','Blueweave Robe','Crystal Focus'],talents:{Channeling:2,Arc:1,Surge:0}},
 {id:'r6',name:'Bren Hollow',class:'Reaver',level:5,power:47,gear:45,talent:1,knowledge:{ashwarden:5,embermaw:0,vaultheart:0},portrait:'BH',gearItems:['Bonecap','Redscale Vest','Twin Cleavers'],talents:{Fury:2,Bloodrush:1,Execution:0}},
 {id:'r7',name:'Elira Dawn',class:'Oracle',level:5,power:42,gear:40,talent:1,knowledge:{ashwarden:3,embermaw:0,vaultheart:0},portrait:'ED',gearItems:['Sunveil','Pilgrim Wrap','Prayer Rod'],talents:{Insight:2,Grace:1,Foretell:0}},
 {id:'r8',name:'Doran Pike',class:'Templar',level:5,power:43,gear:41,talent:1,knowledge:{ashwarden:7,embermaw:0,vaultheart:0},portrait:'DP',gearItems:['Bronze Helm','Oathplate','Tower Shield'],talents:{Guard:2,Judgement:1,Aegis:0}}
];
function initialState(){return{renown:120,gold:1840,roster:starterRoster,party:{tank:null,healer:null,dps:[null,null,null]},bossKills:{ashwarden:false,embermaw:false,vaultheart:false},reports:[],activity:['The guild charter has been signed.','Eight adventurers answer your call.','The Ashen Vault is now available.']}}
let state=(()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||initialState()}catch{return initialState()}})();
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function roleOf(c){return classes[c.class].role}function bossById(id){return bosses.find(b=>b.id===id)}function charById(id){return state.roster.find(c=>c.id===id)}
function roleLabel(role){return role==='dps'?'Damage':role[0].toUpperCase()+role.slice(1)}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const labels={overview:'Command Overview',roster:'Roster',content:'PvE Content',party:'Party Builder',reports:'Attempt Reports'};pageTitle.textContent=labels[id]||'Cellbound';if(id==='party')renderParty();if(id==='reports')renderReports()}
$$('.nav-btn[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));
function renderTop(){renownEl.textContent=state.renown;goldEl.textContent=state.gold.toLocaleString();rosterCount.textContent=`${state.roster.length} / 12`;dungeonProgress.textContent=`${Object.values(state.bossKills).filter(Boolean).length} / 3 bosses`}
function rosterCard(c){const role=roleOf(c),avgK=Math.round(Object.values(c.knowledge).reduce((a,b)=>a+b,0)/3);return `<article class="char-card" data-role="${role}" style="--glow:${classes[c.class].glow}"><div class="char-top"><div class="char-portrait">${c.portrait}</div><span class="role-tag role-${role}">${roleLabel(role)}</span></div><h3>${c.name}</h3><div class="class">${c.class} · Level ${c.level}</div><div class="char-stats"><div><span>Power</span><b>${c.power}</b></div><div><span>Gear</span><b>${c.gear}</b></div><div><span>Points</span><b>${c.talent}</b></div></div><div class="knowledge-row"><div><span>Avg. Knowledge</span><b>${avgK}%</b></div><div class="knowledge-bar"><i style="width:${avgK}%"></i></div></div><button data-char="${c.id}">VIEW CHARACTER</button></article>`}
function renderRoster(filter='all'){rosterGrid.innerHTML=state.roster.filter(c=>filter==='all'||roleOf(c)===filter).map(rosterCard).join('');rosterGrid.querySelectorAll('[data-char]').forEach(b=>b.addEventListener('click',()=>openCharacter(b.dataset.char)))}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRoster(b.dataset.filter)}));
function renderOverview(){overviewRoster.innerHTML=state.roster.slice(0,5).map(c=>`<div class="mini-row"><div class="avatar">${c.portrait}</div><div><b>${c.name}</b><small>${c.class} · Level ${c.level}</small></div><span class="role-tag role-${roleOf(c)}">${roleLabel(roleOf(c))}</span></div>`).join('');activityLog.innerHTML=state.activity.slice(-6).reverse().map((a,i)=>`<div class="activity-entry"><span>${i===0?'Just now':`${i} event${i>1?'s':''} ago`}</span><b>${a}</b></div>`).join('')}
function renderBosses(){bossList.innerHTML=bosses.map((b,i)=>{const locked=i>0&&!state.bossKills[bosses[i-1].id],known=Math.round(state.roster.reduce((s,c)=>s+(c.knowledge[b.id]||0),0)/state.roster.length);return `<article class="boss-card"><div class="boss-visual" data-rune="${b.rune}" style="--boss-glow:${b.glow}"><span class="boss-number">BOSS ${i+1}</span></div><div class="boss-body"><h3>${b.name}</h3><p>${b.mechanic}</p><div class="boss-meta"><div><span>Guild Knowledge</span><b>${known}%</b></div><div><span>Recommended</span><b>${b.recommended} Power</b></div></div><div class="boss-lock">${state.bossKills[b.id]?'DEFEATED':locked?'LOCKED — DEFEAT PREVIOUS BOSS':'AVAILABLE'}</div></div></article>`}).join('');bossSelect.innerHTML=bosses.map((b,i)=>`<option value="${b.id}" ${i>0&&!state.bossKills[bosses[i-1].id]?'disabled':''}>${b.name}${state.bossKills[b.id]?' — Farm':''}</option>`).join('')}
function openCharacter(id){const c=charById(id),role=roleOf(c);characterDetail.innerHTML=`<div class="detail-hero"><div class="detail-avatar">${c.portrait}</div><div><small class="role-tag role-${role}">${roleLabel(role)}</small><h2>${c.name}</h2><p>${c.class} · Level ${c.level} · Power ${c.power} · Gear ${c.gear}</p></div></div><div class="detail-grid"><section class="detail-card"><h3>Equipment</h3><div class="gear-grid">${c.gearItems.map((g,i)=>`<div class="gear-slot"><span>${['Head','Chest','Weapon'][i]}</span><b>${g}</b></div>`).join('')}</div></section><section class="detail-card"><h3>Talents</h3>${Object.entries(c.talents).map(([name,val])=>`<div class="talent-line"><div><b>${name}</b><span>Rank ${val}</span></div><button data-talent="${name}" ${c.talent<1?'disabled':''}>+</button></div>`).join('')}<p style="color:#667975;font-size:.58rem">Unspent points: <b>${c.talent}</b></p></section><section class="detail-card"><h3>Encounter Knowledge</h3>${bosses.map(b=>`<div class="talent-line"><div><b>${b.name}</b><span>${c.knowledge[b.id]||0}% known</span></div></div>`).join('')}</section><section class="detail-card"><h3>Role Summary</h3><p style="color:#748783;font-size:.65rem;line-height:1.55">${role==='tank'?'Frontline specialist. Absorbs boss pressure and protects the group.':role==='healer'?'Keeps the group alive through sustained and burst damage.':'Responsible for damage output, interrupts and encounter utility.'}</p></section></div>`;characterModal.hidden=false;characterDetail.querySelectorAll('[data-talent]').forEach(b=>b.addEventListener('click',()=>{if(c.talent<1)return;c.talents[b.dataset.talent]++;c.talent--;c.power++;save();openCharacter(c.id);renderAll()}))}
$('[data-close]')?.addEventListener('click',()=>characterModal.hidden=true);characterModal.addEventListener('click',e=>{if(e.target===characterModal)characterModal.hidden=true});
function flatPartyIds(){return[state.party.tank,state.party.healer,...state.party.dps].filter(Boolean)}
function assignChar(id){const c=charById(id),role=roleOf(c);removeChar(id);if(role==='tank')state.party.tank=id;else if(role==='healer')state.party.healer=id;else{const idx=state.party.dps.findIndex(x=>!x);if(idx>=0)state.party.dps[idx]=id;else state.party.dps[0]=id}save();renderParty()}
function removeChar(id){if(state.party.tank===id)state.party.tank=null;if(state.party.healer===id)state.party.healer=null;state.party.dps=state.party.dps.map(x=>x===id?null:x)}
function slotHtml(role,id,index=''){const c=id?charById(id):null,icon=role==='tank'?'🛡':role==='healer'?'✚':'⚔';return `<div class="party-slot ${c?'filled':''}"><div class="slot-role">${icon}</div><div>${c?`<b>${c.name}</b><small>${c.class} · Power ${c.power} · ${roleLabel(role)}</small>`:`<b>${roleLabel(role)} Slot${role==='dps'?` ${Number(index)+1}`:''}</b><small>Select a suitable adventurer</small>`}</div>${c?`<button data-remove="${c.id}">×</button>`:''}</div>`}
function partyReadiness(){const ids=flatPartyIds();if(ids.length<5)return{score:ids.length*12,ready:false,hint:'Assign 1 Tank, 1 Healer and 3 Damage characters.'};const boss=bossById(bossSelect.value||'ashwarden'),chars=ids.map(charById),avgPower=chars.reduce((s,c)=>s+c.power,0)/5,avgK=chars.reduce((s,c)=>s+(c.knowledge[boss.id]||0),0)/5;const score=Math.round(Math.min(100,(avgPower/boss.recommended)*58+avgK*.42));return{score,ready:true,hint:`Average power ${avgPower.toFixed(0)} · Average ${boss.name} knowledge ${avgK.toFixed(0)}%`}}
function renderParty(){partySlots.innerHTML=slotHtml('tank',state.party.tank)+slotHtml('healer',state.party.healer)+state.party.dps.map((id,i)=>slotHtml('dps',id,i)).join('');partySlots.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{removeChar(b.dataset.remove);save();renderParty()}));const selected=new Set(flatPartyIds());partyRoster.innerHTML=state.roster.map(c=>`<button class="party-choice" data-pick="${c.id}" ${selected.has(c.id)?'disabled':''}><div class="avatar">${c.portrait}</div><div><b>${c.name}</b><small>${c.class} · Level ${c.level}</small></div><em>${roleLabel(roleOf(c))} · ${c.power}</em></button>`).join('');partyRoster.querySelectorAll('[data-pick]').forEach(b=>b.addEventListener('click',()=>assignChar(b.dataset.pick)));const r=partyReadiness();readinessFill.style.width=`${r.score}%`;readinessText.textContent=`${r.score}%`;readinessLabel.textContent=r.ready?'READY':'NOT READY';readinessLabel.className=r.ready?'good':'';readinessHint.textContent=r.hint;attemptBtn.disabled=!r.ready}
$('#autoFill').addEventListener('click',()=>{state.party.tank=state.roster.filter(c=>roleOf(c)==='tank').sort((a,b)=>b.power-a.power)[0]?.id||null;state.party.healer=state.roster.filter(c=>roleOf(c)==='healer').sort((a,b)=>b.power-a.power)[0]?.id||null;state.party.dps=state.roster.filter(c=>roleOf(c)==='dps').sort((a,b)=>b.power-a.power).slice(0,3).map(c=>c.id);while(state.party.dps.length<3)state.party.dps.push(null);save();renderParty()});bossSelect.addEventListener('change',renderParty);
function simulateAttempt(){const boss=bossById(bossSelect.value),party=flatPartyIds().map(charById);if(party.length!==5)return;attemptModal.hidden=false;let bossHp=100,partyHp=100,tick=0;attemptStage.innerHTML=`<div class="attempt-head"><div><small>DUNGEON ATTEMPT</small><h2>${boss.name}</h2></div><div class="role-tag">THE ASHEN VAULT</div></div><div class="attempt-body"><div class="attempt-raid"><div class="party-column">${party.map(c=>`<div class="sim-unit"><b>${c.name}</b><span>${c.class} · ${roleLabel(roleOf(c))}</span></div>`).join('')}</div><div class="versus">VS</div><div class="boss-column"><div class="sim-unit"><b>${boss.name}</b><span>${boss.mechanic}</span></div><div class="sim-bar sim-boss"><i id="bossSim" style="width:100%"></i></div><div class="sim-bar sim-party"><i id="partySim" style="width:100%"></i></div></div></div><div id="attemptLog" class="attempt-log"></div><div id="attemptResult"></div></div>`;const log=$('#attemptLog'),bossBar=$('#bossSim'),partyBar=$('#partySim'),result=$('#attemptResult');const avgPower=party.reduce((s,c)=>s+c.power,0)/5,avgK=party.reduce((s,c)=>s+(c.knowledge[boss.id]||0),0)/5;const performance=Math.max(.45,avgPower/boss.recommended)*(1+avgK/180);const interval=setInterval(()=>{tick++;const playerDmg=5.8*performance*(.86+Math.random()*.28),bossDmg=Math.max(2.4,6.2/performance)*(.85+Math.random()*.3);bossHp=Math.max(0,bossHp-playerDmg);partyHp=Math.max(0,partyHp-bossDmg);bossBar.style.width=`${bossHp}%`;partyBar.style.width=`${partyHp}%`;const events=[`${boss.name} uses ${tick%3===0?'a major mechanic':'a heavy attack'}.`,`${party[Math.floor(Math.random()*party.length)].name} ${Math.random()>.45?'handles the mechanic cleanly.':'makes a costly mistake.'}`,`Party damage pushes the boss to ${Math.ceil(bossHp)}%.`];log.innerHTML+=events[Math.floor(Math.random()*events.length)]+'<br>';log.scrollTop=log.scrollHeight;if(bossHp<=0||partyHp<=0||tick>=18){clearInterval(interval);resolveAttempt(boss,party,bossHp<=0,result)}} ,420)}
function resolveAttempt(boss,party,success,result){const knowledgeGain=party.map(c=>{const before=c.knowledge[boss.id]||0,gain=success?Math.floor(5+Math.random()*6):Math.floor(7+Math.random()*9),after=Math.min(100,before+gain);c.knowledge[boss.id]=after;return{name:c.name,before,after,gain}});let loot=null;if(success){state.bossKills[boss.id]=true;state.renown+=25;state.gold+=120;const winner=party[Math.floor(Math.random()*party.length)];if(Math.random()<.72){loot=boss.loot[Math.floor(Math.random()*boss.loot.length)];winner.gearItems[2]=loot;winner.gear+=3;winner.power+=3;state.activity.push(`${winner.name} equipped ${loot} from ${boss.name}.`)}state.activity.push(`${boss.name} was defeated in The Ashen Vault.`)}else state.activity.push(`The guild wiped on ${boss.name}, but the team learned from the attempt.`);const report={id:Date.now(),boss:boss.id,success,knowledgeGain,loot,at:new Date().toISOString()};state.reports.unshift(report);save();renderAll();const primary=success?'Boss defeated. The group executed the encounter well enough to secure the kill.':'The group wiped. Encounter knowledge increased, making future attempts more reliable.';result.innerHTML=`<div class="attempt-result"><h3>${success?'VICTORY':'WIPE — PROGRESS MADE'}</h3><p>${primary}</p>${loot?`<div class="loot-drop">Loot acquired: <b>${loot}</b></div>`:''}<p>${knowledgeGain.map(k=>`${k.name}: ${k.before}% → ${k.after}%`).join('<br>')}</p><button id="closeAttempt">RETURN TO GUILD</button></div>`;$('#closeAttempt').addEventListener('click',()=>attemptModal.hidden=true)}
attemptBtn.addEventListener('click',simulateAttempt);attemptModal.addEventListener('click',e=>{if(e.target===attemptModal)attemptModal.hidden=true});
function renderReports(){if(!state.reports.length){reportsList.innerHTML='<div class="panel" style="padding:30px;color:#657874">No attempts yet. Build a party and enter The Ashen Vault.</div>';return}reportsList.innerHTML=state.reports.map(r=>{const b=bossById(r.boss);return `<article class="report-card"><div><div class="report-result ${r.success?'kill':'wipe'}">${r.success?'VICTORY':'WIPE'}</div><small>${new Date(r.at).toLocaleString()}</small></div><div><h3>${b.name}</h3><p>${r.success?'The party defeated the encounter.':'The party failed the encounter but gained meaningful experience.'}${r.loot?` Loot: ${r.loot}.`:''}</p></div><div class="report-gain"><b>Knowledge gained</b>${r.knowledgeGain.map(k=>`<span>${k.name} +${k.gain}%</span>`).join('')}</div></article>`}).join('')}
function renderAll(){renderTop();renderOverview();renderRoster();renderBosses();renderParty();renderReports()}
$('#signOut').addEventListener('click',async()=>{await supabaseClient.auth.signOut();location.replace('./index.html')});
(async()=>{const{data}=await supabaseClient.auth.getSession();if(!data.session?.user){location.replace('./index.html');return}renderAll()})();
})();
