const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),manifest=require('../tools/runtime-manifest.cjs');
const source=name=>fs.readFileSync(manifest.sourcePath(root,name),'utf8');
const sandbox={window:{}};vm.createContext(sandbox);
vm.runInContext(source('blacksmith-forge-v1.js'),sandbox,{filename:'blacksmith-forge-v1.js'});
const F=sandbox.window.CellboundBlacksmithForge;
assert(F?.create&&F?.record&&F?.quality);
assert.equal(F.STAGES.length,3,'forging has three different actions');
assert.equal([...F.STAGES].map(x=>x.key).join(','),'heat,strike,temper');
let f=F.create();
assert.equal(F.isComplete(f),false);
assert.equal(F.quality(f),null,'no quality before all steps');
assert.equal(F.record(f,NaN),null,'invalid marker rejected');
assert.equal(F.record({...f,stage:3},42),null,'fake completed steps rejected');
for(const step of F.STAGES){f=F.record(f,step.target,50);assert(f);assert.equal(f.results.at(-1).label,'PERFECT')}
assert.equal(F.isComplete(f),true);
assert.equal(F.quality(f),100);
assert.equal(F.record(f,40),null,'completed forge cannot repeat steps');
let rough=F.create();for(const step of F.STAGES)rough=F.record(rough,step.target>50?0:100,1);
assert.equal(F.quality(rough),35,'poor timing still yields basic quality');
let near=F.create();for(const step of F.STAGES)near=F.record(near,step.target+11,1);
assert(F.quality(near)>=65&&F.quality(near)<90,'fine quality is distinct');
const economy=source('economy-v2.js'),css=source('economy-v2.css'),html=source('guild.html');
for(const term of ["craftProject.forge&&!Forge?.isComplete?.(craftProject.forge)","if(craftProject.forge&&!Forge?.isComplete?.(craftProject.forge))return;","project.forge?Forge.quality(project.forge):timedCraftQuality(recipe,prof)","22000*Math.max(1,Math.floor(Number(quantity)||1))","function returnReservedInputs(project)","workshopCraftProject","forgeProjectMarkup(prof)","data-forge-strike","data-forge-position"])assert(economy.includes(term),'integration missing '+term);
assert(html.includes('blacksmith-forge-v1.js?v=1'));
assert(css.includes('.forge-timing-track')&&css.includes('@media(prefers-reduced-motion:reduce)'));
assert(manifest.files.includes('blacksmith-forge-v1.js'));
assert(!economy.includes('data-craft-action'),'retired action-step project must not return');
console.log('Job 12A core forge rules, quality tiers, no premature reward, batch-scaled crafting duration and cancellation integration passed.');
