'use strict';
const {chromium,webkit}=require('playwright');
const assert=require('node:assert/strict');
const {mount,matureState}=require('./full-playthrough.browser.cjs');
const engine=process.env.CELLBOUND_TEST_ENGINE==='webkit'?webkit:chromium;
(async()=>{
 const browser=await engine.launch({headless:true,executablePath:process.env.CELLBOUND_TEST_BROWSER||undefined});
 const page=await browser.newPage({viewport:{width:1024,height:1366}});
 page.on('dialog',dialog=>dialog.accept());
 const errors=await mount(page,matureState(),true);
 try{
  await page.waitForFunction(()=>window.CellboundAdmin?.role==='owner'&&window.CellboundDesignBooth&&window.CellboundDesignedContent,{},{timeout:12000});
  await page.evaluate(()=>CellboundGame.switchView('admin'));
  await page.locator('[data-admin-panel-tab="tools"]').click();
  await page.waitForSelector('#designBoothEntry:not([hidden])',{timeout:5000});
  assert.equal(await page.locator('#designBoothEntry').isVisible(),true,'Owner gets a Design Booth entry');
  for(const old of ['#roomEditorEntry','#comicSceneEditorEntry','#dungeonGeneratorEntry','#characterFitViewerEntry']){
   assert.equal(await page.locator(old).isVisible(),false,'Retired separate tool card stays hidden: '+old)
  }
  await page.locator('#openDesignBooth').click();
  await page.waitForSelector('#designBoothMount:not([hidden]) .dbo-shell',{timeout:6000});
  assert.equal(await page.locator('[data-dbo-tool]').count(),8,'Master booth still includes all eight tools');
  assert.equal(await page.locator('[data-dbo-go]').count(),5,'New editors see five obvious starter tasks');
  assert.equal(await page.locator('.dbo-more').count(),1,'Advanced tools are grouped separately');
  await page.locator('[data-dbo-tool="items"]').click();
  await page.waitForSelector('#dboCatalog:not([hidden]) .dbo-catalog-table');
  assert(await page.locator('#dboCatalog').innerText().then(t=>t.includes('Item Catalogue')&&t.includes('catalogue entries')),'Item Catalogue appears in owner admin tools');
  assert.equal(await page.locator('#dboCatalogTier option').count(),7,'Index includes Tier 1–5 and untiered materials');
  assert((await page.locator('.dbo-catalog-table tbody tr').count())>20,'Item catalogue lists existing item definitions');
  await page.locator('#dboCatalogSearch').fill('Frostbound Sigil');
  assert(await page.locator('.dbo-catalog-table tbody').innerText().then(t=>t.includes('Frostbound Sigil')),'Owner can find unique Tier 4 equipment by name');
  await page.locator('#dboCatalogSearch').fill('');
  await page.locator('#dboCatalogCategory').selectOption('Equipment');
  await page.locator('#dboCatalogTier').selectOption('5');
  assert(await page.locator('.dbo-catalog-table tbody tr').first().innerText().then(t=>t.includes('T5')),'Tier 5 equipment is visible in admin catalogue although excluded from normal boss drops');
  await page.locator('#dboCatalogTier').selectOption('all');
  await page.locator('#dboCatalogClass').selectOption('Warrior');
  assert(await page.locator('.dbo-catalog-table tbody tr').first().innerText().then(t=>t.includes('Warrior')),'Class filter narrows catalogue to Warrior');
  await page.locator('#dboCatalogCategory').selectOption('all');
  await page.locator('#dboCatalogClass').selectOption('all');
  const exportPromise=page.waitForEvent('download');
  await page.locator('#dboExportCatalog').click();
  const downloaded=await exportPromise;
  assert.equal(downloaded.suggestedFilename(),'cellbound-item-catalogue.csv','CSV export downloads an importable Google Sheets file');
  await page.locator('[data-dbo-tool="build"]').click();
  await page.locator('#dboNewDungeon').click();
  assert(await page.locator('#dboWorkbench').innerText().then(t=>t.includes('Untitled dungeon')),'Dungeon builder opens');
  assert(await page.locator('#dboReview').innerText().then(t=>t.includes('thing')&&t.includes('Stage 1')),'Builder explains publication blockers in a readable checklist');
  await page.locator('[data-db-step="1"]').click();
  assert.equal(await page.locator('#dboWorkbench [data-db-drop]').count(),0,'Loot is no longer embedded in the fight editor');
  await page.locator('#dboGoToDrops').click();
  await page.waitForSelector('#dboDrops:not([hidden]) #dboBossPicker',{timeout:5000});
  assert((await page.locator('#dboBossPicker option').count())>=19,'Central boss dropdown includes built-in game bosses and a new custom boss');
  const customBoss=await page.locator('#dboBossPicker').inputValue();
  assert(customBoss.startsWith('local:'),'Opened current custom encounter in central loot editor');
  await page.locator('#dboAddLoot').click();
  assert.equal(await page.locator('[data-db-loot-row]').count(),1,'A boss has a compact item row');
  assert.equal(await page.locator('[data-db-drop-row]').count(),1,'Adding an item opens just that item editor');
  assert(await page.locator('[data-db-drop="0.key"] option').count()>0,'Boss gear picker uses approved catalogue items');
  assert(!(await page.locator('[data-db-drop="0.key"]').innerText()).includes('undefined'),'Item picker displays the item names instead of undefined');
  assert(await page.locator('[data-db-loot-row="0"]').innerText().then(t=>t.includes('T1')&&t.includes('25%')),'Tier and drop chance visible without opening editor');
  await page.locator('[data-db-drop="0.kind"]').selectOption('material');
  await page.locator('[data-db-drop="0.key"]').selectOption('hollowroot');
  await page.locator('[data-db-drop="0.chance"]').fill('42');
  await page.locator('[data-db-drop="0.quantity"]').fill('3');
  await page.locator('#dboCloseLootEdit').click();
  assert(await page.locator('[data-db-loot-row="0"]').innerText().then(t=>t.includes('Hollowroot')&&t.includes('42%')&&t.includes('MATERIAL')),'Boss overview immediately lists item name, tier and percentage');
  await page.locator('#dboLootSearch').fill('missing-gear-xyz');
  assert.equal(await page.locator('[data-db-loot-row="0"]').isVisible(),false,'Searching hides non-matching items');
  assert.equal(await page.locator('#dboLootNoMatches').isVisible(),true,'No matches explains empty search');
  await page.locator('#dboLootSearch').fill('hollowroot');
  assert.equal(await page.locator('[data-db-loot-row="0"]').isVisible(),true,'Name search finds the specific material');
  await page.locator('#dboLootTierFilter').selectOption('T1');
  assert.equal(await page.locator('[data-db-loot-row="0"]').isVisible(),false,'Tier filter excludes materials');
  await page.locator('#dboLootTierFilter').selectOption('MATERIAL');
  assert.equal(await page.locator('[data-db-loot-row="0"]').isVisible(),true,'Material filter finds a reagent');
  await page.locator('#dboLootSearch').fill('');
  await page.locator('#dboLootSort').selectOption('chance');
  await page.locator('[data-dbo-tool="build"]').click();
  await page.locator('[data-db-step="0"]').click();
  await page.locator('[data-dbo-tool="drops"]').click();
  await page.locator('#dboBossPicker').selectOption(customBoss);
  assert(await page.locator('[data-db-loot-row="0"]').innerText().then(t=>t.includes('Hollowroot')&&t.includes('42%')),'Item name and percentage survive stage switching');
  await page.locator('[data-db-edit-row="0"]').click();
  assert.equal(await page.locator('[data-db-drop="0.kind"]').inputValue(),'material','Boss drop type survives stage switching');
  assert.equal(await page.locator('[data-db-drop="0.key"]').inputValue(),'hollowroot','Specific reagent selection survives');
  assert.equal(await page.locator('[data-db-drop="0.chance"]').inputValue(),'42','Loot chance survives stage switching');
  assert.equal(await page.locator('[data-db-drop="0.quantity"]').inputValue(),'3','Boss drop quantity survives stage switching');
  await page.locator('#dboBossPicker').selectOption('native:ashen-vault:ashwarden');
  assert(await page.locator('#dboDrops').innerText().then(t=>t.includes('Ash Warden Kael')&&t.includes('extra boss drops')&&t.includes('EXISTING GAME REWARDS')),'Existing dungeon boss is available, with clear default-drop policy');
  await page.locator('#dboAddLoot').click();
  assert.equal(await page.locator('[data-db-loot-row]').count(),1,'Existing boss supports optional owner drop rows');
  assert.equal(await page.locator('#dboSaveNative').isEnabled(),true,'Unsaved boss changes expose an enabled save action');
  assert.equal(await page.locator('#dboDiscardNative').isEnabled(),true,'Unsaved boss changes can safely be discarded');
  await page.locator('#dboDiscardNative').click();
  assert.equal(await page.locator('[data-db-loot-row]').count(),0,'Discard restores the saved boss table without publishing changes');
  await page.locator('#dboAddLoot').click();
  await page.locator('[data-db-remove-drop="0"]').click();
  assert.equal(await page.locator('[data-db-loot-row]').count(),0,'Existing boss row can be removed');
  await page.locator('[data-dbo-tool="build"]').click();
  await page.locator('#dboAddType').selectOption('minigame');
  await page.locator('#dboAddStep').click();
  assert(await page.locator('[data-db-field="step.template"]').count()===1,'Minigame stage editor supports reusable templates');
  assert.equal(await page.locator('[data-db-field="step.answerFriendly"]').count(),1,'Puzzle answer is explained using user-friendly choice numbers');
  await page.locator('[data-db-field="step.answerFriendly"]').fill('2');
  assert.equal(await page.evaluate(()=>CellboundDesignBooth.current().steps.at(-1).answer),1,'Choice 2 maps to the correct zero-based runtime answer');
  await page.locator('[data-db-field="step.template"]').selectOption('sequence');
  await page.locator('[data-db-field="step.sequenceFriendly"]').fill('2, 1, 3');
  assert.equal(await page.evaluate(()=>CellboundDesignBooth.current().steps.at(-1).sequence.join(',')),'1,0,2','New editors enter sequence order using familiar 1-based numbers');
  await page.locator('.dbo-more > summary').click();
  await page.locator('[data-dbo-tool="templates"]').click();
  assert(await page.locator('#dboTemplates').innerText().then(t=>t.includes('Choice Puzzle')&&t.includes('Sequence Puzzle')),'Template library exposes built-in games');
  await page.locator('[data-dbo-tool="rooms"]').click();
  assert.equal(await page.locator('#roomEditorMount .rqe-shell').count(),1,'Existing room editor is a Design Booth tab');
  await page.locator('[data-dbo-tool="comics"]').click();
  await page.waitForFunction(()=>document.querySelector('#comicSceneEditorMount .cse-shell')!=null,{},{timeout:12000});
  await page.locator('[data-dbo-tool="models"]').click();
  assert.equal(await page.locator('#characterFitViewerMount').isVisible(),true,'Character fit viewer is a Design Booth tab');
  await page.locator('#dboClose').click();
  assert.equal(await page.locator('#designBoothMount').isVisible(),false,'Design Booth closes cleanly');
  await page.evaluate(()=>{
    void CellboundDesignedContent.play('qa-preview',{
      content_type:'quest',title:'Design Booth QA',blueprint:{level:1,summary:'Room and puzzle regression',steps:[
        {id:'qa-room',type:'room',title:'Gatehouse',text:'The party enters the chamber.'},
        {id:'qa-minigame',type:'minigame',template:'choice',title:'Rune Door',prompt:'Pick the safe lever',choices:['Left','Right'],answer:1}
      ]}
    });
  });
  await page.waitForSelector('#designAdventureOverlay:not([hidden]) .dbo-player-panel');
  await page.locator('[data-db-advance]').click();
  await page.waitForSelector('#designAdventureOverlay:not([hidden]) [data-db-pick="1"]');
  await page.locator('[data-db-pick="1"]').click();
  await page.locator('[data-db-done]').click();
  await page.waitForFunction(()=>document.querySelector('#designAdventureOverlay .dbo-player-panel')?.textContent?.includes('Adventure complete'),{},{timeout:5000});
  await page.locator('[data-db-finish]').click();
  assert.equal(await page.locator('#designAdventureOverlay').isVisible(),false,'Designed room/minigame run exits cleanly');
  assert.deepEqual(errors,[],'No browser exceptions in owner creative suite');
  console.log(engine===webkit?'WebKit':'Chromium','Design Booth browser regression passed: one entry, eight tabs, searchable item catalogue with CSV export, tier/name/drop-chance boss tables, item filtering, editing and native rewards, newcomer shortcuts, publication checklist, grouped advanced tools, minigames, room/comic/model editors and clean close.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
