const {chromium,webkit}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
(async()=>{
 const browser=await(process.env.CELLBOUND_TEST_ENGINE==='webkit'?webkit:chromium).launch({headless:true});
 const page=await browser.newPage({viewport:{width:1366,height:1024}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.bringToFront();
 const html=read('dist/guild.html').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
 await page.route('https://cellbound.test/**',async route=>{const p=new URL(route.request().url()).pathname;if(p==='/guild.html')return route.fulfill({body:html,contentType:'text/html'});const f=path.resolve(root,'dist',p.slice(1));if(!f.startsWith(path.join(root,'dist')+path.sep)||!fs.existsSync(f))return route.fulfill({status:404,body:''});return route.fulfill({path:f})});
 await page.goto('https://cellbound.test/guild.html');
 await page.evaluate(()=>{
  const roster=Array.from({length:10},(_,i)=>({id:'hero-'+i,name:['Aegis','Mercy','Shade','Ember','Fletch','Rowan','Kestrel','Garrick','Wren','Lyra'][i],class:['Warrior','Priest','Rogue','Mage','Hunter','Druid','Paladin','Warrior','Hunter','Priest'][i],spec:['Protection','Holy','Assassination','Fire','Marksmanship','Restoration','Protection','Arms','Marksmanship','Holy'][i],level:15,power:180,talent:4,equipment:{},professions:[],cellShock:i===9?100:0,role:i===0?'tank':i===1?'healer':'dps'}));
  window.fixture={roster,party:{tank:'hero-0',healer:'hero-1',dps:['hero-2','hero-3','hero-4']},bank:[],activity:[]};window.partyIds=roster.slice(0,5).map(c=>c.id);
  localStorage.setItem('cellbound-management-reboot-v3',JSON.stringify(fixture));
  window.selectView=id=>{document.querySelectorAll('.view').forEach(n=>n.classList.toggle('active',n.id===id));document.querySelector('#pageTitle').textContent=id==='roster'?'The Lantern Inn':id;dispatchEvent(new CustomEvent('cellbound:view-changed',{detail:{view:id}}))};
  window.CellboundGame={ready:true,getState:()=>fixture,getPartyCharacters:()=>partyIds.map(id=>roster.find(c=>c.id===id)),switchView:selectView,characterItemLevel:()=>24,isUnavailable:c=>c.cellShock>=100,isCharacterRosterUnlocked:()=>true,renderAll:()=>{window.fixtureRenderParty?.();dispatchEvent(new CustomEvent('cellbound:state-rendered'))}};
  document.querySelector('#rosterActiveSummary').textContent='10 / 10';document.querySelector('#rosterMetricActive').textContent='5 / 5';document.querySelector('#rosterRecoverySummary').textContent='Company assembled';
  selectView('roster');
 });
 for(const f of ['gear-data.js','character-portraits-v1.js','character-sheet.js'])await page.addScriptTag({content:read(f)});
 await page.evaluate(()=>{fixture.roster.forEach(c=>{c.equipment=Object.fromEntries(CellboundGear.starterSet(c.class).filter(Boolean).map(item=>[item.slot,item]))});localStorage.setItem('cellbound-management-reboot-v3',JSON.stringify(fixture))});
 const guild=read('guild-v4.js');const source={card:guild.slice(guild.indexOf('function rosterCard('),guild.indexOf('function recruitSlotCard(')),slot:guild.slice(guild.indexOf('function slotHtml('),guild.indexOf('function partyReadiness(')),party:guild.slice(guild.indexOf('function renderParty('),guild.indexOf("$('#autoFill')?."))};
 await page.evaluate(source=>{
  const state=fixture,$=s=>document.querySelector(s),ui={partySlots:$('#partySlots'),partyRoster:$('#partyRoster'),readinessFill:$('#readinessFill'),readinessText:$('#readinessText'),readinessLabel:$('#readinessLabel'),readinessHint:$('#readinessHint')};
  const roleOf=c=>c.role,isRosterSlotUnlocked=()=>true,isUnavailable=c=>c.cellShock>=100,characterItemLevel=()=>24,combatClassKey=c=>c.class.toLowerCase(),flatPartyIds=()=>partyIds,partySlotIds=()=>Array.from({length:5},(_,i)=>partyIds[i]||null),charById=id=>state.roster.find(c=>c.id===id),classDef=()=>({glow:'#c5a878',icon:'◇'}),roleLabel=r=>r,portraitHTML=(c,size)=>CellboundPortraits.portraitHTML(c,{size}),formatRemaining=()=> '30m',partyReadiness=()=>({score:partyIds.length*20,ready:partyIds.length===5,hint:'Fixture party'}),save=()=>{},removeChar=id=>{window.partyIds=partyIds.filter(x=>x!==id)},assignChar=id=>{window.partyIds.push(id);renderAll()},renderAll=()=>CellboundGame.renderAll();
  const rosterCard=eval('('+source.card+')'),slotHtml=eval('('+source.slot+')');window.fixtureRenderParty=eval('('+source.party+')');fixtureRenderParty();$('#rosterGrid').innerHTML=state.roster.map(rosterCard).join('');
  $('#rosterSearch').addEventListener('input',e=>{[...$('#rosterGrid').children].forEach((n,i)=>n.style.display=state.roster[i].name.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')});
 },source);
 for(const f of ['living-world-v1.js','lantern-inn-v1.js'])await page.addScriptTag({content:read(f)});
 const shot=async name=>{await page.waitForTimeout(200);await page.screenshot({path:'/tmp/cellbound-inn-'+name+'.png'})};
 await page.locator('.inn-art img').evaluate(img=>img.decode());
 assert.equal(await page.locator('.inn-adventurer').count(),10);assert.equal(await page.locator('.inn-traveller').count(),5);assert.equal(await page.locator('#rosterGrid').isVisible(),false);assert.equal(await page.locator('.inn-world').isVisible(),true);
 assert((await page.locator('.cb-world-avatar').count())>=3,'Warrior, Priest and Rogue use world-avatar prototypes');
 for(const [klass,count] of Object.entries({Warrior:2,Priest:2,Rogue:1}))assert.equal(await page.locator('.cb-world-avatar[data-avatar-class="'+klass+'"]').count(),count,klass+' prototypes match roster');
 const warriorAvatar=page.locator('[data-inn-character="hero-0"] .cb-world-avatar');
 assert.equal(await warriorAvatar.getAttribute('data-avatar-tier'),'1');assert.equal(await warriorAvatar.getAttribute('data-avatar-weapon'),'sword');
 const appearanceBefore=await warriorAvatar.getAttribute('data-appearance-key');
 await page.evaluate(()=>{fixture.roster[0].appearance={race:'Veyren',skinTone:5,face:3,hair:5,hairColor:6,facialHair:3,marking:4,eyes:2,feature:1};dispatchEvent(new CustomEvent('cellbound:state-rendered'))});
 assert.notEqual(await warriorAvatar.getAttribute('data-appearance-key'),appearanceBefore,'appearance data changes world avatar');
 await page.evaluate(()=>{const c=fixture.roster[0];for(const slot of ['Head','Chest','Weapon']){const item=CellboundGear.items.find(x=>x.class==='Warrior'&&x.tier===4&&x.slot===slot);if(item)c.equipment[slot]=item}dispatchEvent(new CustomEvent('cellbound:state-rendered'))});
 assert.equal(await warriorAvatar.getAttribute('data-avatar-tier'),'4','equipped tier changes world avatar family');
 assert.equal(await warriorAvatar.getAttribute('data-avatar-weapon'),'greatsword','equipped weapon type remains visible');

 assert.equal(await page.locator('.inn-adventurer').evaluateAll(nodes=>new Set(nodes.map(n=>n.dataset.locationSlot)).size),10);
 await shot('01-default-ipad');
 await page.locator('[data-inn-character="hero-0"]').click();await page.waitForSelector('#characterModal:not([hidden])');assert(await page.locator('body').evaluate(n=>n.classList.contains('inn-character-open')));await shot('02-character');
 await page.keyboard.press('Escape');await page.waitForSelector('#characterModal[hidden]',{state:'attached'});assert.equal(await page.evaluate(()=>document.activeElement.dataset.innCharacter),'hero-0');
 await page.locator('.inn-ledger').click();await page.locator('#rosterSearch').fill('Mercy');assert.equal(await page.locator('#rosterGrid .roster-character-card:visible').count(),1);assert((await page.locator('#rosterStatusFilter').boundingBox()).height>=44);await shot('03-ledger');await page.locator('#innLedger [data-inn-close]').click();
 await page.locator('.inn-ledger').click();assert.equal(await page.locator('#rosterSearch').inputValue(),'Mercy');await page.keyboard.press('Escape');
 const parent=await page.locator('#party').evaluate(n=>n.parentElement.className);
 await page.locator('.inn-table').click();assert.equal(await page.locator('#innParty #partySlots').count(),1);await shot('04-party');
 await page.locator('#innParty [data-remove="hero-4"]').click();assert.equal(await page.locator('.inn-traveller').count(),4);assert.equal(await page.locator('.inn-adventurer').evaluateAll(nodes=>new Set(nodes.map(n=>n.dataset.locationSlot)).size),10);await page.locator('#innParty [data-pick="hero-5"]').click();assert.equal(await page.locator('[data-inn-character="hero-5"]').evaluate(n=>n.classList.contains('inn-traveller')),true);
 await page.keyboard.press('Escape');assert.equal(await page.locator('#party').evaluate(n=>n.parentElement.className),parent);
 await page.setViewportSize({width:1024,height:768});await shot('05-ipad-landscape');
 await page.setViewportSize({width:390,height:844});await page.locator('.inn-art img').evaluate(img=>img.decode());assert((await page.locator('.inn-art img').evaluate(n=>n.currentSrc)).includes('portrait'));
 await shot('06-mobile');
 for(const n of await page.locator('.inn-adventurer,.inn-hotspot').all()){const b=await n.boundingBox();assert(b.width>=44&&b.height>=44,'touch target');assert(b.x>=0&&b.x+b.width<=390,'within viewport')}
 assert(await page.locator('.inn-adventurer').evaluateAll(nodes=>nodes.every(n=>{const r=n.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('[data-inn-character]')===n})),'all phone characters have an unobstructed selection point');
 await page.locator('[data-inn-character="hero-1"]').click();await page.waitForSelector('#characterModal:not([hidden])');await shot('07-mobile-character');assert((await page.locator('#characterModal .character-modal').boundingBox()).y>180,'room remains visible above bottom sheet');await page.keyboard.press('Escape');
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.inn-figure').first().evaluate(n=>getComputedStyle(n).animationName),'none');
 await page.evaluate(()=>{for(let i=0;i<5;i++)CellboundInn.refresh()});assert.equal(await page.locator('.inn-world').count(),1);assert.equal(await page.locator('#innLedger #rosterSearch').count(),1);
 await page.evaluate(()=>{CellboundGame.switchView=view=>{window.innExitView=view}});await page.locator('.inn-door').click();assert.equal(await page.evaluate(()=>window.innExitView),'home','door uses existing Home navigation');assert.deepEqual(errors,[]);await browser.close();console.log('Lantern Inn: 10 spatial characters, actual character sheet, ledger search persistence, existing party handlers, focus return, iPad/mobile composition and reduced motion passed.');
})().catch(e=>{console.error(e);process.exit(1)});
