/* Run after npm run build. Requires Playwright and its Chromium browser. */
const {chromium,webkit}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await (process.env.CELLBOUND_TEST_ENGINE==='webkit'?webkit:chromium).launch({headless:true,executablePath:process.env.CELLBOUND_TEST_BROWSER||undefined});
 const page=await browser.newPage({viewport:{width:1024,height:768}}),errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('console',msg=>{if(msg.text().includes('visual skipped'))errors.push(msg.text())});
 await page.setContent('<body style="background:#10171d"><div class="cb2d-arena" id="cb2dArena" style="width:900px;height:560px;position:relative"></div></body>');
 for(const f of ['dungeon-2d-v1.css','combat-portraits-v1.css','combat-polish-v2.css','combat-polish-v3.css','combat-physical-v4.css'])await page.addStyleTag({content:fs.readFileSync(path.join(root,'dist',f),'utf8')});
 await page.evaluate(()=>{
  const arena=document.querySelector('#cb2dArena');
  const entries=[['p-t','Tank','warrior',48,50],['p-h','Healer','priest',20,58],['p-m','Mage','mage',25,30],['p-r','Rogue','rogue',58,56],['p-a','Hunter','hunter',24,74],['e-0','Boss','enemy',54,50]];
  for(const [id,name,c,x,y]of entries){const el=document.createElement('div');el.className='cb2d-unit '+(id[0]==='p'?'party class-'+c+' cb-combat-has-portrait':'enemy boss cb-combat-has-boss-portrait');el.dataset.unit=id;el.style.setProperty('--unit-x',x*9+'px');el.style.setProperty('--unit-y',y*5.6+'px');el.innerHTML='<i></i><div class="'+(id[0]==='p'?'cb-combat-portrait':'cb-combat-boss-portrait')+'" style="background:radial-gradient(circle at 40% 30%,#b5a086,#243642);display:grid;place-items:center;color:white">'+name[0]+'</div><span>'+name+'</span><em class="cb2d-unit-hp"><i style="width:100%"></i></em>';arena.appendChild(el)}
  window.send=(type,source='p-t',target='e-0',payload={},extra={})=>window.CellboundCombatFX.combatEvent({type,source,target,timestamp:1000,payload,...extra},{arena});
 });
 for(const f of ['combat-polish-v2.js','combat-polish-v3.js','combat-physical-v4.js'])await page.addScriptTag({content:fs.readFileSync(path.join(root,'dist',f),'utf8')});
 await page.evaluate(()=>send('COMBAT_START'));
 assert.equal(await page.locator('.cbl-facing').count(),6);
 await page.evaluate(()=>{send('ABILITY_START','p-t','e-0',{kind:'damage',range:5});send('DAMAGE_DEALT','p-t','e-0',{targetMax:1000},{amount:35,result:'hit'})});
 const portraitAnimated=await page.evaluate(()=>document.querySelector('[data-unit="p-t"] .cb-combat-portrait').getAnimations().length>0);
 assert(portraitAnimated,'animate the visible portrait');
 assert.equal(await page.locator('.cbl-fx.contact').count(),1,'one impact owner');
 await page.waitForTimeout(600);
 await page.evaluate(()=>send('DAMAGE_DEALT','p-t','e-0',{}, {amount:0,result:'miss'}));
 assert.equal(await page.locator('.cbl-fx.contact').count(),0,'miss cannot hit');
 await page.evaluate(()=>send('DEBUFF_APPLIED','e-0','p-t',{}, {statusEffects:[{id:'stun',cc:'stun'}]}));
 await page.evaluate(()=>send('ABILITY_START','p-t','e-0',{kind:'damage',range:5}));
 assert.equal(await page.locator('[data-unit="p-t"]').getAttribute('data-combat-state'),'controlled');
 await page.evaluate(()=>send('DEBUFF_REMOVED','e-0','p-t',{}, {statusEffects:[{id:'stun'}]}));
 await page.evaluate(()=>{send('CAST_START','p-m','e-0',{duration:700},{ability:'Fireball'});send('CAST_START','p-h','p-t',{duration:900},{ability:'Flash Heal'})});
 assert.equal(await page.locator('.cbl-casting').count(),2,'independent casts overlap');
 await page.waitForTimeout(530);
 assert(await page.locator('.cast-orb').count()>0,'cast travel before resolution');
 await page.evaluate(()=>send('INTERRUPT','e-0','p-m',{}, {result:'success'}));
 assert.equal(await page.locator('[data-unit="p-m"].cbl-casting').count(),0);
 await page.evaluate(()=>send('PLAYER_DEFEATED','e-0','p-r'));
 await page.evaluate(()=>send('ABILITY_START','p-r','e-0',{kind:'damage',range:5}));
 assert.equal(await page.locator('[data-unit="p-r"]').getAttribute('data-combat-state'),'dead');
 await page.evaluate(()=>send('PLAYER_REVIVED','p-h','p-r'));
 assert.equal(await page.locator('[data-unit="p-r"]').getAttribute('data-combat-state'),'reviving');
 await page.evaluate(()=>send('MOVEMENT_START','p-a',null,{to:{x:38,y:70},duration:180}));
 await page.waitForTimeout(210);
 await page.evaluate(()=>send('MOVEMENT_END','p-a',null,{}, {position:{x:38,y:70}}));
 assert.equal(await page.locator('[data-unit="p-a"]').getAttribute('data-x'),'38');
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.evaluate(()=>{send('CAST_START','p-m','e-0',{duration:700});send('INTERRUPT','p-t','e-0',{}, {result:'success'})});
 assert(await page.locator('.cbl-fx.interrupt').count()>0,'reduced motion preserves mechanic feedback');
 await page.screenshot({path:'/tmp/cellbound-living-combat.png'});
 await page.evaluate(()=>{send('COMBAT_END');document.querySelector('#cb2dArena').remove()});
 await page.waitForTimeout(100);
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Living combat browser checks passed: visible portraits, one impact, misses, CC, concurrent casts, travel, interrupts, deaths, revival, movement, reduced motion, cleanup.');
})().catch(e=>{console.error(e);process.exit(1)});
